---

root: "/"

backups: "{{ root }}/var/backups"

roq_conda_channel: "unstable"

redis:
  port: 6379
  docker:
    name: "library/redis"
    tag: "latest"

influxdb:
  port: 8086
  docker:
    name: "library/influxdb"
    tag: "latest"

netdata:
  port: 19999
  docker:
    name: "titpetric/netdata"
    tag: "latest"

grafana:
  port: 3000
  docker:
    name: "grafana/grafana"
    tag: "latest"
  postgres:
    user: "grafana"
    password: "secret"
    database: "grafana"

alertmanager:
  port: 9093
  docker:
    name: "prom/alertmanager"
    tag: "latest"

node_exporter:
  port: 9100
  docker:
    name: "prom/node-exporter"
    tag: "latest"

prometheus:
  port: 9090
  docker:
    name: "prom/prometheus"
    tag: "latest"

postgres:
  port: 5432
  user: "postgres"
  password: "admin"
  docker:
    name: "library/postgres"
    tag: "10"

gogs:
  ssh_port: 10022
  http_port: 10080
  docker:
    name: "gogs/gogs"
    tag: "latest"
  postgres:
    user: "gogs"
    password: "secret"
    database: "gogs"

nexus:
  port: 8081
  docker:
    name: "sonatype/nexus3"
    tag: "latest"

teamcity:
  port: 8111
  docker:
    name: "jetbrains/teamcity-server"
    tag: "latest"
  postgres:
    user: "teamcity"
    password: "secret"
    database: "teamcity"

teamcity_agent:
  docker:
    name: "jetbrains/teamcity-agent"
    tag: "latest"

nginx:
  http_port: 80
  https_port: 443
  docker:
    name: "library/nginx"
    tag: "latest"

# TODO(thraneh): deprecate following

roq_femas:
  metrics:
    port: 12345
    sock: "femas.metrics.sock"
  docker:
    name: "roqtrading/roq-femas"
    tag: "latest"

roq_datafeed:
  metrics:
    port: 12346
    sock: "datafeed.metrics.sock"
  docker:
    name: "roqtrading/roq-datafeed"
    tag: "latest"
