---

root: "/"

backups: "{{ root }}/var/backups"

roq_user: "{{ ansible_user_id }}"

roq_conda_channel: "unstable"

roq_version: "latest"

roq_use_docker: false

alertmanager:
  port: 9093
  docker:
    name: "prom/alertmanager"
    tag: "latest"

# note! name is without -server/-client extension
clickhouse_defaults:
  port: 9000
  http_port: 8123
  metrics_port: 8001
  docker:
    name: "yandex/clickhouse"
    tag: "latest"

gogs_defaults:
  ssh_port: 10022
  http_port: 10080
  docker:
    name: "gogs/gogs"
    tag: "latest"

grafana_defaults:
  port: 3000
  docker:
    name: "grafana/grafana"
    tag: "latest"

influxdb_defaults:
  port: 8086
  docker:
    name: "library/influxdb"
    tag: "latest"

nginx_defaults:
  http_port: 80
  docker:
    name: "library/nginx"
    tag: "latest"

node_exporter:
  port: 9100
  docker:
    name: "prom/node-exporter"
    tag: "latest"

prometheus:
  port: 9090
  docker:
    name: "prom/prometheus"
    tag: "latest"

redis_defaults:
  port: 6379
  docker:
    name: "library/redis"
    tag: "latest"

teamcity:
  port: 8111
  docker:
    name: "jetbrains/teamcity-server"
    tag: "latest"

teamcity_agent:
  docker:
    name: "jetbrains/teamcity-agent"
    tag: "2019.2.4"
#    tag: "latest"

roq_deribit:
  metrics:
    port: 12301
    sock: "deribit.metrics.sock"
  docker:
    name: "roqtrading/roq-deribit"
    tag: "latest"

roq_coinbase_pro:
  metrics:
    port: 12302
    sock: "coinbase-pro.metrics.sock"
  docker:
    name: "roqtrading/roq-coinbase-pro"
    tag: "latest"
