---

root: "/"

backups: "{{ root }}/var/backups"

roq_user: "{{ ansible_user_id }}"

roq_conda_channel: "unstable"

roq_version: "latest"

roq_use_docker: false

# FSH

directory_defaults:
  opt: "{{ (root + '/opt/') | roq_realpath }}"
  run: "{{ (root + '/run/') | roq_realpath }}"
  usr: "{{ (root + '/usr/') | roq_realpath }}"
  usr_local: "{{ (root + '/usr/local/') | roq_realpath }}"
  usr_local_bin: "{{ (root + '/usr/local/bin/') | roq_realpath }}"
  usr_local_etc: "{{ (root + '/usr/local/etc/') | roq_realpath }}"
  var: "{{ (root + '/var/lib/') | roq_realpath }}"
  var_lib: "{{ (root + '/var/lib/') | roq_realpath }}"
  var_log: "{{ (root + '/var/log/') | roq_realpath }}"
  var_tmp: "{{ (root + '/var/tmp/') | roq_realpath }}"
  var_www: "{{ (root + '/var/www/') | roq_realpath }}"

# services

# note! name is without -server/-client extension
clickhouse_defaults:
  port: 9000
  http_port: 8123
  metrics_port: 8001
  docker:
    name: "yandex/clickhouse"
    tag: "latest"

influxdb_defaults:
  port: 8086
  docker:
    name: "library/influxdb"
    tag: "latest"

redis_defaults:
  port: 6379
  docker:
    name: "library/redis"
    tag: "latest"

node_exporter_defaults:
  port: 9100
  docker:
    name: "prom/node-exporter"
    tag: "latest"

prometheus_defaults:
  port: 9090
  docker:
    name: "prom/prometheus"
    tag: "latest"

alertmanager_defaults:
  port: 9093
  docker:
    name: "prom/alertmanager"
    tag: "latest"

grafana_defaults:
  port: 3000
  docker:
    name: "grafana/grafana"
    tag: "latest"

nginx_defaults:
  listen: "0.0.0.0"
  http_port: 80
  docker:
    name: "library/nginx"
    tag: "latest"
  upstream: {}
  server_location: []

# gateways

roq_deribit:
  metrics:
    port: 12301
    sock: "deribit.metrics.sock"
  docker:
    name: "roqtrading/roq-deribit"
    tag: "latest"

roq_coinbase_pro:
  metrics:
    port: 12302
    sock: "coinbase-pro.metrics.sock"
  docker:
    name: "roqtrading/roq-coinbase-pro"
    tag: "latest"
