---

root: "/"

backups: "{{ root }}/var/backups"

redis:
  port: 6379
  service: "localhost"
  docker:
    name: "redis"
    tag: "latest"

influxdb:
  port: 8086
  service: "localhost"
  docker:
    name: "influxdb"
    tag: "latest"

netdata:
  port: 19999
  service: "localhost"
  docker:
    name: "titpetric/netdata"
    tag: "latest"

grafana:
  port: 3000
  service: "localhost"
  docker:
    name: "grafana/grafana"
    tag: "latest"
  postgres:
    user: "grafana"
    password: "secret"
    database: "grafana"

alertmanager:
  port: 9093
  service: "localhost"
  docker:
    name: "prom/alertmanager"
    tag: "latest"

node_exporter:
  port: 9100
  service: "localhost"
  docker:
    name: "prom/node-exporter"
    tag: "latest"

prometheus:
  port: 9090
  service: "localhost"
  docker:
    name: "prom/prometheus"
    tag: "latest"

postgres:
  port: 5432
  service: "localhost"
  user: "postgres"
  password: "admin"
  docker:
    name: "postgres"
    tag: "latest"

gogs:
  ssh_port: 10022
  http_port: 10080
  service: "localhost"
  docker:
    name: "gogs/gogs"
    tag: "latest"
  postgres:
    user: "gogs"
    password: "secret"
    database: "gogs"

nexus:
  port: 8081
  service: "localhost"
  docker:
    name: "sonatype/nexus3"
    tag: "latest"

teamcity:
  port: 8111
  service: "localhost"
  docker:
    name: "jetbrains/teamcity-server"
    tag: "latest"
  postgres:
    user: "teamcity"
    password: "secret"
    database: "teamcity"

teamcity_agent:
  docker:
    name: "jetbrains/teamcity-agent"
    tag: "latest"

nginx:
  port: 80
  service: "localhost"
  docker:
    name: "nginx"
    tag: "latest"

roq_samples:
  docker:
    name: "roqtrading/roq-samples"
    tag: "latest"

roq_femas:
  service: "localhost"
  metrics:
    port: 12345
  docker:
    name: "roqtrading/roq-femas"
    tag: "latest"
