---

- name: combine user configuration with defaults
  set_fact:
    roq_samples_config: >
        {{ roq_samples_defaults | combine(roq_samples | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- name: configuration (debug)
  debug:
    var: config
    verbosity: 1
  tags:
    - always

- name: shorter variable name for config
  set_fact:
    config: "{{ roq_samples_config }}"
  tags:
    - roq-samples

- block:

  - name: create required directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0770
    with_items:
      - "{{ root }}/var/lib/roq"
      - "{{ root }}/var/log/roq"
      - "{{ root }}/var/run/roq"
      - "{{ root }}/var/run/roq/collector"

  - name: create run script
    template:
      src: "templates/roq-collector.sh"
      dest: "{{ root }}/usr/local/bin/roq-collector.sh"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0750

  - name: install the roq-samples conda package
    shell: "{{ root }}/miniconda/bin/conda install -y -n base \
      roq-samples{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-samples

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ config.docker.name }}"
      tag: "{{ config.version }}"
      source: pull
      force_source: true
      force_tag: true
      build:
        http_timeout: 600
    when: config.docker.use

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'roq-collector.service'
      - 'roq-collector-stop.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'roq-collector.timer'
      - 'roq-collector-stop.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

  when: "'trading' in group_names"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-samples
