---

- name: detect owner
  set_fact:
    user: "{{ user if roq_user is defined else ansible_user_id }}"
  tags:
    - roq-deribit

- name: combine user configuration with defaults
  set_fact:
    config: >
        {{ roq_deribit_defaults | combine(roq_deribit | default({}), recursive=True) }}
  tags:
    - roq-deribit

- name: configuration (debug)
  debug:
    var: config
    verbosity: 1
  tags:
    - roq-deribit

- block:

  - name: create required directories
    file:
      path: "{{ root }}/{{ item }}"
      state: directory
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0770
    with_items:
      - "/var/lib/roq"
      - "/var/log/roq"
      - "/var/run/roq"

  - name: create run scripts
    template:
      src: "templates/roq-deribit.sh"
      dest: "{{ root }}/usr/local/bin/roq-deribit.sh"
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0750

  - name: install the roq-deribit conda package
    shell: "{{ root }}/miniconda/bin/conda install -y -n base \
      roq-deribit{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
  
  when: "'roq_deribit' in group_names"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-deribit

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ config.docker.name }}"
      tag: "{{ config.version }}"
      source: pull
      force_tag: true
      build:
        http_timeout: 600
    when: config.docker.use

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - 'roq-deribit.service'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  when: become_user is defined and 'roq_deribit' in group_names
  become: true
  tags:
    - roq-deribit
