---

- name: combine user configuration with defaults
  set_fact:
    roq_deribit_config: >
        {{ roq_deribit_defaults | combine(roq_deribit | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- block:

  - name: shorter variable name for config
    set_fact:
      config: "{{ roq_deribit_config }}"

  - name: install
    include_role:
      name: common
      tasks_from: gateway

  when: "'roq_deribit' in group_names"
  tags:
    - roq-deribit
