---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
    - "{{ root }}/etc/redis"
    - "{{ root }}/var/lib/redis"
    notify:
    - reload redis

  - name: create config file
    template:
      src: "templates/redis.conf"
      dest: "{{ root }}/etc/redis/redis.conf"
      owner: root
      group: root
      mode: 0644
    register: redis_service
    notify:
    - reload redis

  - name: pull docker image
    docker_image:
      name: "redis"
      http_timeout: 300

  - name: create systemd service
    template:
      src: "templates/redis.service"
      dest: "/etc/systemd/system/redis.service"
      owner: root
      group: root
      mode: 0644
    register: redis_service

  - name: enable the redis service
    systemd:
      name: "redis.service"
      enabled: true
      daemon_reload: true
    when: redis_service.changed

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - redis
