---

- name: detect owner
  set_fact:
    user: "{{ user if roq_user is defined else ansible_user_id }}"
  tags:
    - redis

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
    - "{{ root }}/etc/redis"
    - "{{ root }}/var/lib/redis"
    notify:
    - restart redis

  - name: create config file
    template:
      src: "templates/redis.conf"
      dest: "{{ root }}/etc/redis/redis.conf"
      owner: root
      group: root
      mode: 0644
    register: redis_service
    notify:
    - restart redis

  - name: pull docker image
    docker_image:
      name: "{{ redis.docker.name }}"
      tag: "{{ redis.docker.tag }}"
      force: true
      http_timeout: 300

  - name: create systemd service
    template:
      src: "templates/redis.service"
      dest: "/etc/systemd/system/redis.service"
      owner: root
      group: root
      mode: 0644
    register: redis_service

  - name: enable the redis service
    systemd:
      name: "redis.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: redis_service.changed

  - name: create redis-cli script
    template:
      src: "templates/redis-cli"
      dest: "{{ root }}/usr/local/bin/redis-cli"
      owner: "{{ user }}"
      mode: 0750

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - redis
