---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
    - "{{ directory_config.usr_local_etc }}/redis"
    - "{{ directory_config.var_lib }}/redis"
    notify:
    - restart redis

  - name: create config file
    template:
      src: "templates/redis.conf"
      dest: "{{ directory_config.usr_local_etc }}/redis/redis.conf"
      owner: root
      group: root
      mode: 0644
    register: redis_service
    notify:
    - restart redis

  - name: pull docker image
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ redis_config.docker.name }}"
      tag: "{{ redis_config.docker.tag }}"
      source: pull
      force_source: true
      force_tag: true

  - name: create systemd service
    template:
      src: "templates/redis-server.service"
      dest: "/etc/systemd/system/redis-server.service"
      owner: root
      group: root
      mode: 0644
    register: redis_service

  - name: enable the redis service
    systemd:
      name: "redis-server.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: redis_service.changed

  - name: create shell script
    template:
      src: "templates/redis-cli"
      dest: "{{ directory_config.usr_local_bin }}/redis-cli"
      owner: "{{ roq_user }}"
      mode: 0755

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - redis
