---

##############
### COMMON ###
##############

- block:

  - name: create required directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ directory_config.opt }}"
      - "{{ directory_config.run }}"
      - "{{ directory_config.usr }}"
      - "{{ directory_config.usr_local }}"
      - "{{ directory_config.usr_local_bin }}"
      - "{{ directory_config.usr_local_etc }}"
      - "{{ directory_config.var }}"
      - "{{ directory_config.var_lib }}"
      - "{{ directory_config.var_log }}"  # XXX review (only used by teamcity)

# TODO(thraneh): or maybe the condition should be root != '/' ?
  when: become_user is not defined
  tags:
    - baseline

##############
### DEBIAN ###
##############

- block:

  - name: update packages
    apt:
      update_cache: yes
    when: not upgrade_system

  - name: update and upgrade packages
    apt:
      upgrade: dist
      update_cache: yes
    when: upgrade_system | bool

  when: ansible_os_family == "Debian" and become_user is defined
  become: true
  tags:
    - baseline

##############
### REDHAT ###
##############

- block:

  - name: update and upgrade packages
    yum:
      name: '*'
      state: latest
    when: upgrade_system | bool

  # TODO(thraneh): use 'ansible_lsb.major_release|int' to get '7'?
  - name: download epel-release-latest
    get_url:
      url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      dest: "{{ directory_config.opt }}"
    when: install_epel_release == true

  - name: install epel-release from download
    yum:
      name: "{{ directory_config.opt }}/epel-release-latest-7.noarch.rpm"
      state: present
    when: install_epel_release == true

  - name: install epel-release
    yum:
      name: epel-release
      state: present

  when: ansible_os_family == "RedHat" and become_user is defined
  become: true
  tags:
    - baseline
