---

roq_kraken_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-kraken"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "kraken"
    config_file: "{{ root }}/usr/local/etc/roq-kraken/config.toml"
    event_log_dir: "{{ root }}/var/lib/roq/data"
    client_listen_address: "{{ root }}/run/roq/roq-kraken.sock"
    metrics_listen_address: "{{ root }}/run/roq/metrics/roq-kraken.sock"
    rest_uri: "https://api.kraken.com"
    ws_public_uri: "wss://beta-ws.kraken.com"
    ws_private_uri: "wss://beta-ws-auth.kraken.com"
  symbols:
    - ".*"
