---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ root }}/var/www"
      - "{{ root }}/var/www/html"
      - "{{ root }}/etc/nginx"
      - "{{ root }}/etc/nginx/conf.d"
    notify:
    - reload nginx
  
  - name: create index.html
    template:
      src: "templates/index.html"
      dest: "{{ root }}/var/www/html/index.html"
      owner: root
      mode: 0644
    when: '"trading" in groups'
  
  - name: available sites
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/etc/nginx/conf.d/{{ item }}"
      owner: root
      mode: 0644
    with_items:
      - nginx.conf
    notify:
      - restart nginx
  
  - name: docker pull images
    docker_image:
      name: "nginx"
      tag: "latest"
      http_timeout: 300
  
  - name: create systemd service
    template:
      src: "templates/nginx.service"
      dest: "/etc/systemd/system/nginx.service"
      owner: root
      group: root
      mode: 0644
    register: nginx_service
    notify:
    - restart nginx

  - name: enable the nginx service
    systemd:
      name: "nginx.service"
      state: started
      enabled: true
      daemon_reload: true
    when: nginx_service.changed

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - nginx
