---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ directory_config.var_log }}/nginx"
      - "{{ directory_config.var_www }}"
      - "{{ directory_config.usr_local_etc }}/nginx"
      - "{{ directory_config.usr_local_etc }}/nginx/conf.d"
    notify:
    - reload nginx
  
  - name: available sites
    template:
      src: "templates/{{ item }}"
      dest: "{{ directory_config.usr_local_etc }}/nginx/conf.d/{{ item }}"
      owner: root
      mode: 0644
    with_items:
      - nginx.conf
    notify:
      - restart nginx
  
  - name: logrotate
    template:
      src: "templates/logrotate.conf"
      dest: "{{ directory_config.etc }}/logrotate.d/nginx"
      owner: root
      mode: 0644
    notify:
      - restart logrotate

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ nginx_config.docker.name }}"
      tag: "{{ nginx_config.docker.tag }}"
      source: pull
      force_source: true
      force_tag: true
    notify:
      - restart nginx
  
  - name: create systemd service
    template:
      src: "templates/nginx.service"
      dest: "/etc/systemd/system/nginx.service"
      owner: root
      group: root
      mode: 0644
    register: nginx_service
    notify:
    - restart nginx

  - name: enable the nginx service
    systemd:
      name: "nginx.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: nginx_service.changed

  when: become_user is defined
  become: true
  tags:
    - nginx
