---

roq_coinbase_pro_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-coinbase-pro"
  cpu: {}
  logging:
    verbosity: 0
  collect:
    size: 0
    path: "{{ root }}/var/tmp/roq-coinbase-pro.roq"
    sync_freq_secs: 600
