---

roq_coinbase_pro_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-coinbase-pro"
  options: {}
  cpu_affinity: {}
  logging:
    verbosity: 0
  event_log:
    dir: "{{ root }}/var/lib/roq/roq-coinbase-pro/"
    sync_freq_secs: 600
  options: {}
