---

roq_coinbase_pro_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-coinbase-pro"
  cpu_affinity: {}
  logging:
    verbosity: 0
  event_log:
    file_size: 0
    file_path: "{{ root }}/var/tmp/roq-coinbase-pro.roq"
    sync_freq_secs: 600
  options: {}
