---

benchmark_use_docker: true

benchmark_defaults:
  version: "{{ roq_benchmark.docker.tag }}"
  docker:
    name: "{{ roq_benchmark.docker.name }}"
  cpu: {}
  logging:
    use_log_dir: false
    verbosity: 0
