---

roq_bitmex_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-bitmex"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "bitmex"
    config_file: "{{ directory_config.usr_local_etc }}/roq-bitmex/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-bitmex.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-bitmex.sock"
    rest_uri: "https://testnet.bitmex.com"
    ws_uri: "wss://testnet.bitmex.com/realtime"
  symbols:
    - ".*"
