---

roq_bitmex_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-bitmex"
  options: {}
  cpu_affinity: {}
  logging:
    verbosity: 0
  net:
    fix_mkt: "tcp://8.44.203.78:1529"
    fix_ord: "tcp://8.44.203.78:1528"
    fix_drp_uri: "tcp://8.44.203.78:1530"
  event_log:
    dir: "{{ root }}/var/lib/roq/roq-bitmex/"
    sync_freq_secs: 600
  options: {}
  market_data:
    sender: "TODO"
    target: "TODO"
  order_entry:
    sender: "TODO"
    target: "TODO"
  drop_copy:
    sender: "TODO"
    target: "TODO"
