---

roq_bitmex_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-bitmex"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  cpu_affinity: {}
  logging:
    verbosity: 0
  name: "bitmex"
  net:
    ws: "wss://testnet.bitmex.com/realtime"
    rest: "https://testnet.bitmex.com"
  event_log:
    dir: "{{ root }}/var/lib/roq"
    sync_freq_secs: 600
  options: {}
  symbols:
    - ".*"
