---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ root }}/var/lib/grafana"
      - "{{ root }}/etc/grafana"
      - "{{ root }}/etc/grafana/provisioning"
      - "{{ root }}/etc/grafana/provisioning/datasources"
      - "{{ root }}/etc/grafana/provisioning/dashboards"
    notify:
    - restart grafana

  - name: provision datasources
    template:
      src: "templates/datasources.yml"
      dest: "/etc/grafana/provisioning/datasources/all.yml"
      owner: root
      group: root
      mode: 0644
    notify:
    - restart grafana
  
  - name: provision dashboards
    template:
      src: "templates/{{ item }}"
      dest: "/etc/grafana/provisioning/dashboards/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - "femas-gateway.json"
    notify:
    - restart grafana
  
  - name: provision dashboards
    template:
      src: "templates/dashboards.yml"
      dest: "/etc/grafana/provisioning/dashboards/all.yml"
      owner: root
      group: root
      mode: 0644
    notify:
    - restart grafana
  
  - name: pull docker image
    docker_image:
      name: "{{ grafana.docker.name }}"
      tag: "{{ grafana.docker.tag }}"
      http_timeout: 300
  
  - name: create systemd service
    template:
      src: "templates/grafana.service"
      dest: "/etc/systemd/system/grafana.service"
      owner: root
      group: root
      mode: 0644
    register: grafana_service
    notify:
    - restart grafana
  
  - name: enable the grafana service
    systemd:
      name: "grafana.service"
      state: started
      enabled: true
      daemon_reload: true
    when: grafana_service.changed
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - grafana
