---

roq_huobi_futures_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-huobi-futures"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "huobi-futures"
    config_file: "{{ directory_config.usr_local_etc }}/roq-huobi-futures/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-huobi-futures.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-huobi-futures.sock"
    rest_uri: "https://testnet.huobi-futures.com"
    ws_uri: "wss://testnet.huobi-futures.com/realtime"
  symbols:
    - ".*"
