---

- hosts: all
  roles:
    - kernel
    - chrony
    - sysstat
    - sysadmin
    - python
    - docker

- hosts: web
  roles:
    - certbot

- hosts: secure
  roles:
    - sshd
    - fail2ban

- hosts: onload
  roles:
    - onload

- hosts: all
  roles:
    - conda
    - postgres

- hosts: dev
  roles:
    - toolchain

- hosts: trading
  roles:
    - roq-samples

- hosts: roq-femas
  roles:
    - roq-femas

- hosts: trading
  roles:
    - redis
    - influxdb
    - netdata
    - prometheus
    - grafana

- hosts: cicd
  roles:
    - gogs
    - nexus
    - teamcity

- hosts: all
  roles:
    - nginx
