---

- hosts: all
  pre_tasks:
    - name: check ansible minimum required version
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You should use an updated version of Ansible, version 2.7 or higher is required"

- hosts: all
  roles:
    - config
    - baseline
    - kernel
    - chrony
    - python
    - docker

- hosts: onload
  roles:
    - onload

- hosts: all
  roles:
    - conda

- hosts: dev
  roles:
    - toolchain
    - virtualbox
    - vagrant

- hosts: trading
  roles:
    - clickhouse
    - influxdb
    - redis

- hosts: roq_simulator
  roles:
    - roq-simulator

- hosts: roq_clickhouse
  roles:
    - roq-clickhouse

- hosts: roq_influxdb
  roles:
    - roq-influxdb

- hosts: roq_redis
  roles:
    - roq-redis

- hosts: roq_binance
  roles:
    - roq-binance

- hosts: roq_bitmex
  roles:
    - roq-bitmex

- hosts: roq_bitstamp
  roles:
    - roq-bitstamp

- hosts: roq_coinbase_pro
  roles:
    - roq-coinbase-pro

- hosts: roq_deribit
  roles:
    - roq-deribit

- hosts: roq_ftx
  roles:
    - roq-ftx

- hosts: roq_gemini
  roles:
    - roq-gemini

- hosts: roq_hitbtc
  roles:
    - roq-hitbtc

- hosts: roq_kraken
  roles:
    - roq-kraken

- hosts: trading
  roles:
    - prometheus
    - grafana

- hosts: cicd
  roles:
    - gogs
    - teamcity

- hosts: all
  roles:
    - nginx
    - roq-backup
