---

# TODO(thraneh): change to ansible user

- hosts: all
  remote_user: root
  become_user: root
  roles:
  - baseline
  - sysadmin
  - python
  - conda  # deprecate when docker has been fully implemented

- hosts: trading
  remote_user: root
  become_user: root
  roles:
  - tuning
  - docker
  - infra  # deprecate when docker has been fully implemented
  - nginx
  - redis
  - netdata
  - prometheus
  - roq-trading

- hosts: development
  remote_user: root
  become_user: root
  roles:
  - devtools
