---

- hosts: all
  pre_tasks:
    - name: check ansible minimum required version
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You should use an updated version of Ansible, version 2.7 or higher is required"

- hosts: all
  roles:
    - baseline
    - kernel
    - chrony
    - sysstat
    - sysadmin
    - python
    - docker

- hosts: web
  roles:
    - certbot

- hosts: secure
  roles:
    - sshd
    - fail2ban

- hosts: onload
  roles:
    - onload

- hosts: all
  roles:
    - conda
    - postgres

- hosts: dev
  roles:
    - toolchain
    - virtualbox
    - vagrant

- hosts: trading
  roles:
    - redis
    - influxdb

- hosts: roq_benchmark
  roles:
    - roq-benchmark

- hosts: roq_samples
  roles:
    - roq-samples

- hosts: roq_simulator
  roles:
    - roq-simulator

- hosts: roq_influxdb
  roles:
    - roq-influxdb

- hosts: roq_coinbase_pro
  roles:
    - roq-coinbase-pro

- hosts: roq_deribit
  roles:
    - roq-deribit

- hosts: roq_femas
  roles:
    - roq-femas

- hosts: roq_datafeed
  roles:
    - roq-datafeed

- hosts: trading
  roles:
    - prometheus
    - grafana

- hosts: cicd
  roles:
    - gogs
    - nexus
    - teamcity

- hosts: all
  roles:
    - nginx
