---

# Groups:
#   trading  -- install a trading server with required services
#   web      -- install a web server with the required services
#   secure   -- secure the server (sshd, fail2ban and firewall)
#   onload   -- install the solarflare onload driver
#   dev      -- install the conda build toolchain
#   database -- install database services (redis and influxdb)
#   samples  -- install roq-samples
#   femas    -- install roq-femas

- hosts: all
  roles:
    - baseline

- hosts: trading,web,teamcity
  roles:
    - kernel
    - chrony
    - sysstat
    - sysadmin
    - python
    - docker

- hosts: secure
  roles:
    - sshd
    - fail2ban

- hosts: onload
  roles:
    - onload

- hosts: all
  roles:
    - conda

- hosts: dev
  roles:
    - toolchain

- hosts: trading
  roles:
    - roq-samples

- hosts: roq-femas
  roles:
    - roq-femas

- hosts: trading
  roles:
    - redis
    - influxdb
    - netdata
    - prometheus
    - grafana

- hosts: nexus
  roles:
    - nexus

- hosts: teamcity
  roles:
    - teamcity

- hosts: web
  roles:
    - certbot

- hosts: trading,web,teamcity
  roles:
    - nginx
