---

- hosts: all
  pre_tasks:
    - name: check ansible minimum required version
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You should as an updated version of Ansible, version 2.7 or higher is required"

- hosts: all
  roles:
    - baseline
    - kernel
    - chrony
    - sysstat
    - sysadmin
    - python
    - docker

- hosts: web
  roles:
    - certbot

- hosts: secure
  roles:
    - sshd
    - fail2ban

- hosts: onload
  roles:
    - onload

- hosts: all
  roles:
    - conda
    - postgres

- hosts: dev
  roles:
    - toolchain

- hosts: trading
  roles:
    - roq-samples

- hosts: roq-femas
  roles:
    - roq-femas

- hosts: roq-datafeed
  roles:
    - roq-datafeed

- hosts: trading
  roles:
    - redis
    - influxdb
    - netdata
    - prometheus
    - grafana

- hosts: cicd
  roles:
    - gogs
    - nexus
    - teamcity

- hosts: all
  roles:
    - nginx

- hosts: reboot
  roles:
    - reboot
