---
femasapi:
  md_user:
    front: "tcp://1.2.3.4:8105"
    name_server: "tcp://1.2.3.4:5213"
  trader:
    front: "tcp://1.2.3.4:8102"
    name_server: "tcp://1.2.3.4:5213"
  accounts:
    "00000000":
      broker: "0000"
      password: "000000"
      symbols:
        CFFEX:
        - "${IC}"
        - "${IF}"
        - "${IH}"
        - "${T_}"
        - "${TF}"
      master: true
  users:
    test:
      password: "1234"
      symbols:
        CFFEX:
        - ".*"
        SHFE:
        - ".*"
    trader:
      password: "secret"
      accounts:
      - "00000000"
      symbols:
        CFFEX:
        - "${IC}"
      limits:
        create_order:
          max: 10
          monitor_period: 60s
          ban_period: 300s
  license: "90879bedfcb0316528dd41d3b12d7df718fd3c479486c7271b4ff7605bfa395e"
