---

roq_binance_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-binance-futures"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "binance-futures"
    config_file: "{{ directory_config.usr_local_etc }}/roq-binance-futures/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-binance-futures.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-binance-futures.sock"
    rest_uri: "https://testnet.binancefuture.com"
    ws_uri: "wss://stream.binancefuture.com/ws"
  symbols:
    - ".*"
