---

- name: combine user configuration with defaults
  set_fact:
    roq_simulator_config: >
        {{ roq_simulator_defaults | combine(roq_simulator | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- name: debug
  debug:
    var: roq_simulator_config
    verbosity: 1
  tags:
    - always

- name: shorter variable name for config
  set_fact:
    config: "{{ roq_simulator_config }}"
  tags:
    - roq-simulator

- block:

  - name: create required directories
    file:
      path: "{{ root }}/{{ item }}"
      state: directory
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0770
    with_items:
      - "/var/lib/roq"
      - "/var/log/roq"
      - "/var/run/roq"

  - name: create config
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/usr/local/etc/{{ item }}"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0640
    with_items:
      - "roq-simulator.gflags"
      - "roq-simulator.toml"

  - name: create run scripts
    template:
      src: "templates/roq-simulator.sh"
      dest: "{{ root }}/usr/local/bin/roq-simulator.sh"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0750

  - name: install the roq-simulator conda package
    shell: "{{ root }}/opt/miniconda3/bin/conda install -y -n base \
      roq-simulator{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
  
  - name: install the roq-data conda package
    shell: "{{ root }}/opt/miniconda3/bin/conda install -y -n base \
      roq-data{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"

  when: "'roq_simulator' in group_names"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-simulator

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ config.docker.name }}"
      tag: "{{ config.version }}"
      source: pull
      force_source: true
      force_tag: true
    when: config.docker.use

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - 'roq-simulator.service'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  when: become_user is defined and 'roq_simulator' in group_names
  become: true
  tags:
    - roq-simulator
