---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
    - "{{ root }}/var/lib/gogs"
    notify:
    - restart gogs

  - name: create directories (locked down)
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0750
    with_items:
    - "{{ root }}/var/lib/gogs/backups"
    notify:
    - restart gogs

  - name: create directories (ownership managed by docker image)
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ root }}/var/lib/gogs/data"
    - "{{ root }}/var/lib/gogs/data/gogs"
    - "{{ root }}/var/lib/gogs/data/gogs/conf"
    notify:
    - restart gogs

  - name: create app.ini
    template:
      src: "templates/app.ini"
      dest: "{{ root }}/var/lib/gogs/data/gogs/conf/app.ini"
      mode: 0644
    notify:
    - restart gogs

  - name: pull docker image
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ gogs_config.docker.name }}"
      tag: "{{ gogs_config.docker.tag }}"
      source: pull
      force_source: true
      force_tag: true
    notify:
    - restart gogs

  - name: create systemd service
    template:
      src: "templates/gogs.service"
      dest: "/etc/systemd/system/gogs.service"
      owner: root
      group: root
      mode: 0644
    register: gogs_service

  - name: enable the gogs service
    systemd:
      name: "gogs.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: gogs_service.changed

  - name: create shell script
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/usr/local/bin/{{ item }}"
      owner: "{{ roq_user }}"
      mode: 0755
    with_items:
      - "gogs-backup"

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'gogs-backup.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'gogs-backup.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: disable systemd services
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_services }}"

  - name: enable and start systemd timers
    systemd:
      name: "{{ item }}"
      enabled: true
      state: started
      daemon_reload: true
    with_items: "{{ systemd_timers }}"

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - gogs
