#!/usr/bin/env bash

set -e

ARGS="${@:-"--flagfile={{ directory_config.usr_local_etc }}/roq-clickhouse/options.gflags"}"

"{{ directory_config.opt }}/conda/bin/roq-clickhouse" "{{ directory_config.var_lib }}/roq/data" "$ARGS"
