#!/usr/bin/env bash

set -e

ARGS="${@:-"--flagfile={{ (root + '/usr/local/etc/roq-clickhouse/options.gflags') | roq_realpath }}"}"

"{{ (root + '/opt/conda/bin/roq-clickhouse') | roq_realpath }}" "{{ (root + '/var/lib/roq/data') | roq_realpath }}" "$ARGS"
