---

- name: detect owner
  set_fact:
    user: "{{ user if roq_user is defined else ansible_user_id }}"
  tags:
    - teamcity

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0700
    with_items:
      - "{{ root }}/var/lib/teamcity"
    notify:
    - restart teamcity
    - restart teamcity-agent

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ root }}/var/log/teamcity"
    notify:
    - restart teamcity

  - name: create directories
    file:
      path: "{{ root }}/etc/teamcity-agent-{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_sequence: start=1 end={{ teamcity_agent_count | int }}
    notify:
    - restart teamcity-agent

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ root }}/opt/ansible"
      - "{{ root }}/opt/ansible/docker"
      - "{{ root }}/opt/ansible/docker/roq-tc-agent"
  
  - name: create encrypted password
    shell: "echo -n `echo -n {{ teamcity.postgres.password }}{{ teamcity.postgres.user }} | md5sum | awk '{print $1}'`"
    register: encrypted_password

  - name: create postgres user
    postgresql_user:
      name: "{{ teamcity.postgres.user }}"
      password: "md5{{ encrypted_password.stdout_lines[0] }}"
      encrypted: true
      role_attr_flags: "CREATEDB,NOSUPERUSER"
      login_host: "localhost"
      port: "{{ postgres.port }}"
      login_user: "{{ postgres.user }}"
      login_password: "{{ postgres.password }}"
    notify:
    - restart teamcity

  - name: create postgres database
    postgresql_db:
      name: "{{ teamcity.postgres.database }}"
      encoding: "UTF-8"
      owner: "{{ teamcity.postgres.user }}"
      login_host: "localhost"
      port: "{{ postgres.port }}"
      login_user: "{{ postgres.user }}"
      login_password: "{{ postgres.password }}"
    notify:
    - restart teamcity

  - name: grant postgres user priviliges
    postgresql_privs:
      db: "{{ teamcity.postgres.database }}"
      privs: "ALL"
      objs: "ALL_IN_SCHEMA"
      role: "{{ teamcity.postgres.user }}"
      login_host: "localhost"
      port: "{{ postgres.port }}"
      login_user: "{{ postgres.user }}"
      login_password: "{{ postgres.password }}"
    notify:
    - restart teamcity
  
# server

  - name: pull docker image
    docker_image:
      name: "{{ teamcity.docker.name }}"
      tag: "{{ teamcity.docker.tag }}"
      force: true
      http_timeout: 300

  - name: create systemd service
    template:
      src: "templates/teamcity.service"
      dest: "/etc/systemd/system/teamcity.service"
      owner: root
      group: root
      mode: 0644
    register: teamcity_server_service
    notify:
    - restart teamcity
  
  - name: enable the teamcity service
    systemd:
      name: "teamcity.service"
      state: started
      enabled: true
      daemon_reload: true
    when: teamcity_server_service.changed

  - name: create scripts
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/usr/local/bin/{{ item }}"
      owner: "{{ user }}"
      mode: 0750
    with_items:
      - "teamcity-backup.sh"

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'teamcity-backup.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'teamcity-backup.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

# agent

  - name: pull docker image
    docker_image:
      name: "{{ teamcity_agent.docker.name }}"
      tag: "{{ teamcity_agent.docker.tag }}"
      force: true
      http_timeout: 300
  
  - name: create dockerfile
    template:
      src: "templates/Dockerfile"
      dest: "/opt/ansible/docker/roq-tc-agent/Dockerfile"

  - name: build customized agent
    docker_image:
      name: "roq-tc-agent"
      tag: "latest"
      force: true
      path: "/opt/ansible/docker/roq-tc-agent"

  - name: create systemd services
    template:
      src: "templates/teamcity-agent.service"
      dest: "/etc/systemd/system/teamcity-agent-{{ item }}.service"
      owner: root
      group: root
      mode: 0644
    with_sequence: start=1 end={{ teamcity_agent_count | int }}
    notify:
    - restart teamcity-agent
  
  - name: enable the teamcity agent services
    systemd:
      name: "teamcity-agent-{{ item }}.service"
      state: started
      enabled: true
      daemon_reload: true
    with_sequence: start=1 end={{ teamcity_agent_count | int }}
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - teamcity
