#!/usr/bin/env bash

set -e

ARGS="${@:-"--flagfile={{ (root + '/usr/local/etc/roq-redis/options.gflags') | roq_realpath }}"}"

"{{ (root + '/opt/conda/bin/roq-redis') | roq_realpath }}" "{{ (root + '/var/lib/roq') | roq_realpath }}" "$ARGS"
