---

##############
### DEBIAN ###
##############

- block:

  - name: install
    apt:
      name: vagrant
      state: present

  when: ansible_os_family == "Debian" and become_user is defined
  become: true
  tags:
    - vagrant
  
##############
### REDHAT ###
##############

- block:

  - name: install
    yum:
      name: "https://releases.hashicorp.com/vagrant/{{ vagrant_defaults.version }}/vagrant_{{ vagrant_defaults.version }}_x86_64.rpm"
      state: present

  when: ansible_os_family == "RedHat" and become_user is defined
  become: true
  tags:
    - vagrant
