{
 "title": "roq-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "max(node_hwmon_temp_celsius)" }
   ]
  },
  {
   "title": "Frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_cpu_frequency_hertz) / 1000 / 1000 / 1000"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    { "expr": "irate(node_intr_total[1m])" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_Active_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "EDAC",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_edac_uncorrectable_errors_total"
    }
   ]
  },
  {
   "title": "Device Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_device_error)"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (max(node_filesystem_free_bytes{device!=\"tmpfs\"}) by (device) / max(node_filesystem_size_bytes{device!=\"tmpfs\"}) by (device))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Critical Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_hwmon_temp_crit_celsius)"
    }
   ]
  },
  {
   "title": "Max Frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_cpu_frequency_max_hertz) / 1000 / 1000 / 1000"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(node_context_switches_total[1m])"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_Dirty_bytes" }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))"
    }
   ]
  },
  {
   "title": "Binance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"binance\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"binance\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"binance\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"binance\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"binance\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 2 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"binance\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 2 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"binance\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"binance\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"binance\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"binance\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"binance\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"binance\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"binance\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"binance\", event=\"connect\"}) - max(roq_clients{source=\"binance\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "BitMEX (Ireland)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"bitmex\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"bitmex\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"bitmex\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"bitmex\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"bitmex\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"bitmex\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"bitmex\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"bitmex\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"bitmex\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"bitmex\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"bitmex\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"bitmex\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"bitmex\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"bitmex\", event=\"connect\"}) - max(roq_clients{source=\"bitmex\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "BitStamp (Germany)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"bitstamp\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"bitstamp\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"bitstamp\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"bitstamp\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"bitstamp\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"bitstamp\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"bitstamp\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"bitstamp\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"bitstamp\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"bitstamp\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"bitstamp\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"bitstamp\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"bitstamp\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"bitstamp\", event=\"connect\"}) - max(roq_clients{source=\"bitstamp\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Coinbase PRO (USA, VA)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"coinbase-pro\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"coinbase-pro\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"coinbase-pro\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"coinbase-pro\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"coinbase-pro\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"coinbase-pro\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"coinbase-pro\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"coinbase-pro\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"coinbase-pro\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"coinbase-pro\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"coinbase-pro\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"coinbase-pro\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"coinbase-pro\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"coinbase-pro\", event=\"connect\"}) - max(roq_clients{source=\"coinbase-pro\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Deribit (UK)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"deribit\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"deribit\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"deribit\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"deribit\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"deribit\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"deribit\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"deribit\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"deribit\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"deribit\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"deribit\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"deribit\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"deribit\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"deribit\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"deribit\", event=\"connect\"}) - max(roq_clients{source=\"deribit\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "FTX (Singapore)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"ftx\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"ftx\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"ftx\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"ftx\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 10 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"ftx\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"ftx\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"ftx\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"ftx\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"ftx\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"ftx\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"ftx\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"ftx\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"ftx\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"ftx\", event=\"connect\"}) - max(roq_clients{source=\"deribit\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Gemini (USA, NJ)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"gemini\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"gemini\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"gemini\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"gemini\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"gemini\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 11 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"gemini\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"gemini\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"gemini\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"gemini\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"gemini\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"gemini\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"gemini\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"gemini\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"gemini\", event=\"connect\"}) - max(roq_clients{source=\"gemini\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "HitBTC (Germany)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"hitbtc\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"hitbtc\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"hitbtc\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"hitbtc\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"hitbtc\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"hitbtc\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"hitbtc\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"hitbtc\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"hitbtc\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"hitbtc\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"hitbtc\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"hitbtc\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"hitbtc\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"hitbtc\", event=\"connect\"}) - max(roq_clients{source=\"gemini\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kraken",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"kraken\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Market Data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"kraken\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Order Manager",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(absent(roq_updated{source=\"kraken\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "roq_exceptions{source=\"kraken\"}"
      }
     ]
    },
    {
     "title": "Events (total)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(roq_events_count{source=\"kraken\"})"
      }
     ]
    },
    {
     "title": "Events (frequency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 13 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_count{source=\"kraken\"}[1m])"
      }
     ]
    },
    {
     "title": "Processing (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 13 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum{source=\"kraken\"}[1m]) / on (source, connection, function) irate(roq_profile_count{source=\"kraken\"}[1m]) / 1000"
      }
     ]
    },
    {
     "title": "External (latency)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(roq_latency_sum{source=\"kraken\", function=\"ping\"}[1m]) / on(source, connection, function) irate(roq_latency_count{source=\"kraken\"}[1m]) / 1000000"
      }
     ]
    },
    {
     "title": "Disconnects",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (connection) (roq_counter{source=\"kraken\",function=\"disconnect\"})",
       "legendFormat": "{{connection}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - roq_process{source=\"kraken\",name=\"start_time\"}"
      }
     ]
    },
    {
     "title": "Market by Price",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 15 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{source=\"kraken\", function=\"market_by_price\"}[1m]))"
      }
     ]
    },
    {
     "title": "Working Orders",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(roq_clients{source=\"kraken\", event=\"connect\"}) - max(roq_clients{source=\"kraken\", event=\"disconnect\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Working Orders",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "Internal Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 10, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{function=~\"create_order|modify_order|cancel_order\"}[1m])) by(source)"
      }
     ]
    },
    {
     "title": "Awaiting Response",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 10, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{function=~\"create_order|modify_order|cancel_order\"}[1m])) by(source) - sum(irate(roq_profile_count{function=~\"create_order_ack|modify_order_ack|cancel_order_ack\"}[1m])) by(source)"
      }
     ]
    }
   ]
  },
  {
   "title": "Debug (gateways)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events (encoded messages)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(roq_events_count[1m])" }
     ]
    },
    {
     "title": "Events (encode latency)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_events_sum[1m]) / on (source, function) irate(roq_events_count[1m]) / 1000"
      }
     ]
    },
    {
     "title": "Encoding > .5μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_events_bucket{le=\"500\"}[1m]) / on (source, function) irate(roq_events_count[1m])"
      }
     ]
    },
    {
     "title": "Encoding > 1μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_events_bucket{le=\"1000\"}[1m]) / on (source, function) irate(roq_events_count[1m])"
      }
     ]
    },
    {
     "title": "Encoding > 2μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_events_bucket{le=\"2000\"}[1m]) / on (source, function) irate(roq_events_count[1m])"
      }
     ]
    },
    {
     "title": "Profile (measurements)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(roq_profile_count[1m])" }
     ]
    },
    {
     "title": "Profile (processing latency)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_profile_sum[1m]) / on (source, connection, function) irate(roq_profile_count[1m]) / 1000"
      }
     ]
    },
    {
     "title": "Processing > 2μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_profile_bucket{le=\"2000\"}[1m]) / on (source, connection, function) irate(roq_profile_count[1m])"
      }
     ]
    },
    {
     "title": "Processing > 5μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 70 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_profile_bucket{le=\"5000\"}[1m]) / on (source, connection, function) irate(roq_profile_count[1m])"
      }
     ]
    },
    {
     "title": "Processing > 10μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_profile_bucket{le=\"10000\"}[1m]) / on (source, connection, function) irate(roq_profile_count[1m])"
      }
     ]
    },
    {
     "title": "Heartbeat (client <--> server latency)",
     "type": "graph",
     "description": "Represented as 1-way latency",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(roq_heartbeat_latency_sum[1m]) / on (receiver, sender) irate(roq_heartbeat_latency_count[1m]) / 1000"
      }
     ]
    },
    {
     "title": "Heartbeat > 1μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_heartbeat_latency_bucket{le=\"1000\"}[1m]) / on (sender, receiver) irate(roq_heartbeat_latency_count[1m])"
      }
     ]
    },
    {
     "title": "Heartbeat > 2μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 82 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_heartbeat_latency_bucket{le=\"2000\"}[1m]) / on (sender, receiver) irate(roq_heartbeat_latency_count[1m])"
      }
     ]
    },
    {
     "title": "Heartbeat > 5μs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - irate(roq_heartbeat_latency_bucket{le=\"5000\"}[1m]) / on (sender, receiver) irate(roq_heartbeat_latency_count[1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Debug (system)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(node_interrupts_total{cpu=~\"[1-6]\",info!~\".*timer.*\"}[1m])"
      }
     ]
    },
    {
     "title": "Major Faults",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgmajfault[1m])"
      }
     ]
    },
    {
     "title": "Minor Faults",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(node_vmstat_pgfault[1m])" }
     ]
    },
    {
     "title": "Pages In",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(node_vmstat_pgpgin[1m])" }
     ]
    },
    {
     "title": "Pages Out",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(node_vmstat_pgpgout[1m])" }
     ]
    }
   ]
  },
  {
   "title": "Feed Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "absent(rate(node_systemd_unit_state{name=\"roq-influxdb.service\",state=\"active\"}[10s])) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Aux",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "InfluxDB",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(node_systemd_unit_state{name=\"influxdb.service\",state=\"active\"})"
      }
     ]
    },
    {
     "title": "Redis",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(node_systemd_unit_state{name=\"redis.service\",state=\"active\"})"
      }
     ]
    }
   ]
  }
 ]
}