---

roq_bitstamp_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-bitstamp"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "bitstamp"
    config_file: "{{ root }}/etc/roq/roq-bitstamp.toml"
    event_log_dir: "{{ root }}/var/lib/roq"
    client_listen_address: "{{ root }}/var/tmp/roq-bitstamp.sock"
    metrics_listen_address: "{{ root }}/var/tmp/roq-bitstamp_metrics.sock"
    ws_uri: "wss://ws.bitstamp.net"
    rest_uri: "https://www.bitstamp.net"
    fix_uri: "tcp+ssl://fix.bitstamp.net:8905"
    allow_price_inversion: true
  symbols:
    - ".*"
