---

roq_redis_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-redis"
  name: "redis"
  logging:
    verbosity: 0
  flags:
    name: "redis"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-redis.sock"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    uri: "tcp://localhost:6379"
