---

roq_redis_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-redis"
  name: "redis"
  logging:
    verbosity: 0
  options:
    name: "redis"
    metrics_listen_address: "{{ root }}/run/roq/metrics/roq-redis.sock"
    event_log_dir: "{{ root }}/var/lib/roq/data"
    uri: "tcp://localhost:6379"
