---

roq_redis_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-redis"
  name: "redis"
  logging:
    verbosity: 0
  options:
    name: "redis"
    uri: "tcp://localhost:6379"
