---

- name: combine user configuration with defaults
  set_fact:
    roq_tools_config: >
        {{ roq_tools_defaults | combine(roq_tools | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- name: configuration (debug)
  debug:
    var: config
    verbosity: 1
  tags:
    - always

- name: shorter variable name for config
  set_fact:
    config: "{{ roq_tools_config }}"
  tags:
    - roq-tools

- block:

  - name: check previous version
    shell: '{{ directory_config.opt }}/conda/bin/conda list -f roq-tools | sed -n "s/^roq-tools\s*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"'
    register: previous_version
    changed_when: false

  - name: install conda package
    shell: "{{ directory_config.opt }}/conda/bin/conda install -y -n base \
      roq-tools{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
    changed_when: false

  - name: check current version
    shell: '{{ directory_config.opt }}/conda/bin/conda list -f roq-tools | sed -n "s/^roq-tools\s*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"'
    register: current_version
    changed_when: "current_version.stdout != previous_version.stdout"
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-tools
