---

##############
### COMMON ###
##############

- block:

  - name: define list of common packages
    set_fact:
      common_packages:
      - htop
      - iotop
      - iftop
      - dstat
      - lsof
      - wget
      - curl
      - vim
      - bash-completion
      - traceroute
      - whois
      - bzip2
      - zip
      - unzip
      - socat

  tags:
    - sysadmin

##############
### DEBIAN ###
##############

- block:

  - name: define list of debian specific packages
    set_fact:
      debian_packages:
      - mailutils

  - name: install tools
    apt:
      name: '{{ common_packages }} + {{ debian_packages }}'
      state: present

  when: ansible_os_family == "Debian" and become_user is defined
  become: true
  tags:
    - sysadmin
  
##############
### REDHAT ###
##############

- block:

  - name: define list of redhat specific packages
    set_fact:
      redhat_packages:
      - mailx
      - net-tools  # ifconfig

  - name: install tools
    yum:
      name: '{{ common_packages }} + {{ redhat_packages }}'
      state: present

  when: ansible_os_family == "RedHat" and become_user is defined
  become: true
  tags:
    - sysadmin
  
##############
### COMMON ###
##############

- block:

  - name: bash profile -- default editor + avoid history leaks
    become: true
    template:
      src: "templates/profile.sh"
      dest: "/etc/profile.d/00-aliases.sh"
      owner: root
      mode: 0644
    tags:
    - sysadmin
    - bash

  when: become_user is defined
  become: true
  tags:
    - sysadmin
