---

- name: detect owner
  set_fact:
    user: "{{ user if roq_user is defined else ansible_user_id }}"
  tags:
    - roq-datafeed

- name: combine configuration with defaults
  set_fact:
    datafeed_config: '{{ datafeed_defaults | combine(datafeed | default({})) }}'
  tags:
    - roq-datafeed

- block:

  - name: create required directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0770
    with_items:
      - "{{ root }}/etc/roq"
      - "{{ root }}/etc/roq/datafeed"
      - "{{ root }}/var/log/roq"
      - "{{ root }}/var/run/roq"
      - "{{ root }}/var/run/roq/datafeed"

  - name: create run script
    template:
      src: "templates/roq-datafeed.sh"
      dest: "{{ root }}/usr/local/bin/roq-datafeed.sh"
      owner: "{{ user }}"
      mode: 0750
  
  - name: create config files
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/etc/roq/datafeed/{{ item }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0640
    with_items:
      - "master.conf"
      - "users.conf"
      - "symbols.conf"
      - "accounts.conf"
      - "datafeed.conf"
      - "variables.conf"
      - "license.conf"

  - name: install the roq-datafeed conda package
    shell: "{{ root }}/miniconda/bin/conda install -y -n base roq-datafeed{{ '' if datafeed_config.version == 'latest' else '==%s'|format(datafeed_config.version) }}"
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-datafeed

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ datafeed_config.docker.name }}"
      tag: "{{ datafeed_config.version }}"
      force: true
      http_timeout: 300

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'roq-datafeed.service'
      - 'roq-datafeed-stop.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'roq-datafeed.timer'
      - 'roq-datafeed-stop.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

  when: "'roq-datafeed' in group_names"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-datafeed

#############################
### WORKAROUND FOR ROQ-11 ###
#############################

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ root }}/opt/ansible"
      - "{{ root }}/opt/ansible/docker"
      - "{{ root }}/opt/ansible/docker/roq-datafeed-bridge"

  - name: create dockerfile
    template:
      src: "templates/Dockerfile"
      dest: "/opt/ansible/docker/roq-datafeed-bridge/Dockerfile"

  - name: build customized agent
    docker_image:
      name: "roq-datafeed-bridge"
      tag: "latest"
      force: true
      path: "/opt/ansible/docker/roq-datafeed-bridge"

  - name: define list of systemd units needed to bridge tcp into docker network
    set_fact:
      workaround_services:
      - "roq-datafeed-unix-to-tcp.service"

  - name: create systemd units for bridging tcp into docker network
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ workaround_services }}"

  - name: enable systemd units for bridging tcp into docker network
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items: "{{ workaround_services }}"

  - name: start systemd units for bridging tcp into docker network
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ workaround_services }}"

  when: "'roq-datafeed' in group_names and not datafeed_use_docker"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-datafeed
