---

##############
### DEBIAN ###
##############

- block:

  - name: install pip
    apt:
      name:
        - python-setuptools
        - python-pip

  when: ansible_os_family == "Debian" and not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) and become_user is defined
  become: true
  tags:
    - python

- block:

  - name: install pip3
    apt:
      name:
        - python-setuptools
        - python3-pip

  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20 and become_user is defined
  become: true
  tags:
    - python

##############
### REDHAT ###
##############

- block:

  - name: install pip
    yum:
      name: python-setuptools
  
  - name: easy install pip
    easy_install:
      name: pip
      state: latest

  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8 and become_user is defined
  become: true
  tags:
    - python
