---

- name: restart teamcity
  service:
    name: teamcity
    state: restarted
    enabled: yes
  become: true

- name: restart teamcity-agent-1
  service:
    name: teamcity-agent-1
    state: restarted
    enabled: yes
  become: true
