#!/usr/bin/env bash

set -e

BIN="{{ (directory_config.opt + '/conda/bin/roq-' + config.options.name) | roq_realpath }}"

ARGS="${@:-"--flagfile={{ (directory_config.usr_local_etc + '/roq-' + config.options.name) | roq_realpath }}/options.gflags"}"

if [[ $- == *i* ]]; then
  exec "$BIN" "$ARGS"
else
  "$BIN" "$ARGS"
fi
