#!/usr/bin/env bash

set -e

BIN="{{ (root + '/opt/conda/bin/roq-' + config.options.name) | roq_realpath }}"

ARGS="${@:-"--flagfile={{ (root + '/usr/local/etc/roq-' + config.options.name) | roq_realpath }}/options.gflags"}"

if [[ $- == *i* ]]; then
  exec "$BIN" "$ARGS"
else
  "$BIN" "$ARGS"
fi
