---

- name: combine user configuration with defaults
  set_fact:
    roq_kafka_config: >
        {{ roq_kafka_defaults | combine(roq_kafka | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- name: configuration (debug)
  debug:
    var: config
    verbosity: 1
  tags:
    - always

- name: shorter variable name for config
  set_fact:
    config: "{{ roq_kafka_config }}"
  tags:
    - roq-kafka

- block:

  - name: create required directories
    file:
      path: "{{ root }}/{{ item }}"
      state: directory
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0755
    with_items:
      - "/var/lib/roq"
      - "/var/lib/roq/event-logs"
      - "/usr/local/etc/roq-kafka"

  - name: create config
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/usr/local/etc/roq-kafka/{{ item }}"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0640
    with_items:
      - "options.gflags"

  - name: create shell script
    template:
      src: "templates/roq-kafka"
      dest: "{{ root }}/usr/local/bin/roq-kafka"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0755

  - name: check previous version
    shell: '{{ root }}/opt/conda/bin/conda list -f roq-kafka | sed -n "s/^roq-kafka\s*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"'
    register: previous_version
    changed_when: false

  - name: install conda package
    shell: "{{ root }}/opt/conda/bin/conda install -y -n base \
      roq-kafka{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
    changed_when: false

  - name: check current version
    shell: '{{ root }}/opt/conda/bin/conda list -f roq-kafka | sed -n "s/^roq-kafka\s*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"'
    register: current_version
    changed_when: "current_version.stdout != previous_version.stdout"
  
  when: "'roq_kafka' in group_names"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-kafka

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ config.docker.name }}"
      tag: "{{ config.version }}"
      source: pull
      force_source: true
      force_tag: true
    when: config.docker.use

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - 'roq-kafka.service'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  when: become_user is defined and 'roq_kafka' in group_names
  become: true
  tags:
    - roq-kafka
