---

- block:

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'reboot.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'reboot.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - reboot
