{
 "title": "roq-benchmark (ping-pong)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Round Trip Latency (receiver → sender → receiver)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_round_trip_latency_sum[1m]) / on (receiver, sender) irate(roq_round_trip_latency_count[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Average (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_round_trip_latency_sum[10m])) / sum(irate(roq_round_trip_latency_count[10m])) / 1000.0"
    }
   ]
  },
  {
   "title": "> 2µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_round_trip_latency_bucket{le=\"2000\"}[1m]) / on (receiver, sender) irate(roq_round_trip_latency_count[1m])))"
    }
   ]
  },
  {
   "title": "> 2µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_round_trip_latency_bucket{le=\"2000\"}[10m]) / on (receiver, sender) irate(roq_round_trip_latency_count[10m])))"
    }
   ]
  },
  {
   "title": "> 5µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_round_trip_latency_bucket{le=\"5000\"}[1m]) / on (receiver, sender) irate(roq_round_trip_latency_count[1m])))"
    }
   ]
  },
  {
   "title": "> 5µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_round_trip_latency_bucket{le=\"5000\"}[10m]) / on (receiver, sender) irate(roq_round_trip_latency_count[10m])))"
    }
   ]
  },
  { "title": "Processing Latency (internal)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_profile_sum{function=\"market_by_price\",source=~\"client.*\"}[1m]) / on (source) irate(roq_profile_count{function=\"market_by_price\",source=~\"client.*\"}[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Average (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 7 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_profile_sum{function=\"market_by_price\"}[10m])) / sum(irate(roq_profile_count{function=\"market_by_price\"}[10m])) / 1000.0"
    }
   ]
  },
  {
   "title": "> 2µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_profile_bucket{function=\"market_by_price\", le=\"2000\"}[1m]) / on (source) irate(roq_profile_count{function=\"market_by_price\"}[1m])))"
    }
   ]
  },
  {
   "title": "> 2µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_profile_bucket{function=\"market_by_price\", le=\"2000\"}[10m]) / on(source) irate(roq_profile_count{function=\"market_by_price\"}[10m])))"
    }
   ]
  },
  {
   "title": "> 5µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_profile_bucket{function=\"market_by_price\", le=\"5000\"}[1m]) / on (source) irate(roq_profile_count{function=\"market_by_price\"}[1m])))"
    }
   ]
  },
  {
   "title": "> 5µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_profile_bucket{function=\"market_by_price\", le=\"5000\"}[10m]) / on(source) irate(roq_profile_count{function=\"market_by_price\"}[10m])))"
    }
   ]
  },
  {
   "title": "IPC Latency (sender → receiver)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_inter_process_latency_sum[1m]) / on (receiver, sender) irate(roq_inter_process_latency_count[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Average (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 13 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_inter_process_latency_sum[10m])) / sum(irate(roq_inter_process_latency_count[10m])) / 1000.0"
    }
   ]
  },
  {
   "title": "> 2µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_inter_process_latency_bucket{le=\"2000\"}[1m]) / on (receiver, sender) irate(roq_inter_process_latency_count[1m])))"
    }
   ]
  },
  {
   "title": "> 2µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_inter_process_latency_bucket{le=\"2000\"}[10m]) / on(receiver, sender) irate(roq_inter_process_latency_count[10m])))"
    }
   ]
  },
  {
   "title": "> 5µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_inter_process_latency_bucket{le=\"5000\"}[1m]) / on (receiver, sender) irate(roq_inter_process_latency_count[1m])))"
    }
   ]
  },
  {
   "title": "> 5µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_inter_process_latency_bucket{le=\"5000\"}[10m]) / on(receiver, sender) irate(roq_inter_process_latency_count[10m])))"
    }
   ]
  },
  {
   "title": "Heartbeat Round Trip (receiver → sender → receiver)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_heartbeat_latency_sum[1m]) / on (receiver, sender) irate(roq_heartbeat_latency_count[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Average (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 19 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_heartbeat_latency_sum[10m])) / sum(irate(roq_heartbeat_latency_count[10m])) / 1000.0"
    }
   ]
  },
  {
   "title": "> 2µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (irate(roq_heartbeat_latency_bucket{le=\"2000\"}[1m]) / on (receiver, sender) irate(roq_heartbeat_latency_count[1m])))"
    }
   ]
  },
  {
   "title": "> 2µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_heartbeat_latency_bucket{le=\"2000\"}[10m]) / on(receiver, sender) irate(roq_heartbeat_latency_count[10m])))"
    }
   ]
  },
  {
   "title": "> 5µs (conditional distribution)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_heartbeat_latency_bucket{le=\"5000\"}[10m]) / on(receiver, sender) irate(roq_heartbeat_latency_count[10m])))"
    }
   ]
  },
  {
   "title": "> 5µs (10 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (1 - irate(roq_profile_bucket{function=\"market_by_price\", le=\"5000\"}[10m]) / on(source) irate(roq_profile_count{function=\"market_by_price\"}[10m])))"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "°C" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius" }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "GHz" }
   ],
   "targets": [
    {
     "expr": "(node_cpu_frequency_hertz) / 1000000000"
    }
   ]
  },
  {
   "title": "Total (non-idle)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "System (non-idle and non-user)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (irate(node_cpu_seconds_total{mode=~\"iowait|irq|softirq|steal|system\"}[5m])) * 100"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_Active_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Dirty",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Dirty_bytes" }
   ]
  },
  {
   "title": "Writeback",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Writeback_bytes" }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(avg(irate(node_disk_io_time_seconds_total[10m])) by (device)) by (device))/10"
    }
   ]
  },
  {
   "title": "Client",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_profile_sum{function=\"market_by_price\",source=~\"client.*\"}[1m]) / on (source, function) irate(roq_profile_count{function=\"market_by_price\",source=~\"client.*\"}[1m]) / 1000"
    },
    {
     "expr": "irate(roq_profile_sum{function=\"send_to\",source=~\"client.*\"}[1m]) / on (source, function) irate(roq_profile_count{function=\"send_to\",source=~\"client.*\"}[1m]) / 1000"
    },
    {
     "expr": "irate(roq_profile_sum{function=\"create_order\",source=~\"client.*\"}[1m]) / on (source, function) irate(roq_profile_count{function=\"create_order\",source=~\"client.*\"}[1m]) / 1000"
    },
    {
     "expr": "irate(roq_profile_sum{function=~\"custom.*\",source=~\"client.*\"}[1m]) / on (source, function) irate(roq_profile_count{function=~\"custom.*\",source=~\"client.*\"}[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_profile_sum{function=\"market_by_price\",source=~\"server.*\"}[1m]) / on (source, function) irate(roq_profile_count{function=\"market_by_price\",source=~\"server.*\"}[1m]) / 1000"
    },
    {
     "expr": "irate(roq_profile_sum{function=\"send_to\",source=~\"server.*\"}[1m]) / on (source, function) irate(roq_profile_count{function=\"send_to\",source=~\"server.*\"}[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Profile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_profile_sum[1m]) / on (source, function) irate(roq_profile_count[1m]) / 1000"
    }
   ]
  }
 ]
}