{
 "title": "WIP -- Femas Gateway (Roq Trading Solutions)",
 "description": "Gateway internal metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "roq-femas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(node_systemd_unit_state{name=\"roq-femas.service\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "roq-collector",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(node_systemd_unit_state{name=\"roq-collector.service\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "netdata",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(node_systemd_unit_state{name=\"netdata.service\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(node_systemd_unit_state{name=\"node-exporter.service\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(node_systemd_unit_state{name=\"prometheus.service\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Alertmanager",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(node_systemd_unit_state{name=\"alertmanager.service\",state=\"active\"})"
    }
   ]
  },
  { "title": "CST", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 } },
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Exceptions (count)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "roq_femas_gateway_exceptions" }
   ]
  },
  {
   "title": "Request (frequency)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(roq_femas_gateway_order_action{type=\"create_order\"}[1m]) * 60"
    }
   ]
  },
  {
   "title": "Response (count)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "roq_femas_gateway_order_update" }
   ]
  },
  {
   "title": "Hit Ratio (%)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100.0 * sum(roq_femas_gateway_order_update{type=\"completed\"}) / sum(roq_femas_gateway_order_update)"
    }
   ]
  },
  {
   "title": "Gateway <--> Client (latency measured as: heartbeat round-trip / 2)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Connections (count)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "roq_femas_client_connections{type=\"accepted\"} - ignoring(type) roq_femas_client_connections{type=\"closed\"}"
    }
   ]
  },
  {
   "title": "Latency (usecs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_heartbeat_latency_sum[2m]) / rate(roq_femas_heartbeat_latency_count[2m])"
    }
   ]
  },
  {
   "title": "% (Latency > 10 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_heartbeat_latency_bucket{le=\"10\"}[2m])) / sum(rate(roq_femas_heartbeat_latency_count[2m]))))"
    }
   ]
  },
  {
   "title": "% (Latency > 25 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_heartbeat_latency_bucket{le=\"25\"}[2m])) / sum(rate(roq_femas_heartbeat_latency_count[2m]))))"
    }
   ]
  },
  {
   "title": "Gateway (front-end event processing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Events (count)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "roq_femas_gateway_count" }
   ]
  },
  {
   "title": "Latency (usecs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_gateway_sum[2m]) / rate(roq_femas_gateway_count[2m])"
    }
   ]
  },
  {
   "title": "% (Latency > 10 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_gateway_bucket{le=\"10\"}[2m])) / sum(rate(roq_femas_gateway_count[2m]))))"
    }
   ]
  },
  {
   "title": "Frequency (per second)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_gateway_count[2m])"
    }
   ]
  },
  {
   "title": "% (Latency > 25 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_gateway_bucket{le=\"25\"}[2m])) / sum(rate(roq_femas_gateway_count[2m]))))"
    }
   ]
  },
  {
   "title": "Gateway (internal message passing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Events (count)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "roq_femas_queue_count" }
   ]
  },
  {
   "title": "Latency (usecs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_queue_sum[2m]) / rate(roq_femas_queue_count[2m])"
    }
   ]
  },
  {
   "title": "% (Latency > 10 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_queue_bucket{le=\"10\"}[2m])) / sum(rate(roq_femas_queue_count[2m]))))"
    }
   ]
  },
  {
   "title": "Frequency (per second)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_queue_count[2m])"
    }
   ]
  },
  {
   "title": "% (Latency > 25 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_queue_bucket{le=\"25\"}[2m])) / sum(rate(roq_femas_queue_count[2m]))))"
    }
   ]
  },
  {
   "title": "Gateway (back-end event processing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Events (count)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "roq_femas_callback_count" }
   ]
  },
  {
   "title": "Latency (usecs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_callback_sum[2m]) / rate(roq_femas_callback_count[2m])"
    }
   ]
  },
  {
   "title": "% (Latency > 10 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_callback_bucket{le=\"10\"}[2m])) / sum(rate(roq_femas_callback_count[2m]))))"
    }
   ]
  },
  {
   "title": "Frequency (per second)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_callback_count[1m])"
    }
   ]
  },
  {
   "title": "% (Latency > 25 usecs)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(rate(roq_femas_callback_bucket{le=\"25\"}[2m])) / sum(rate(roq_femas_callback_count[2m]))))"
    }
   ]
  },
  { "title": "Process (system statistics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roq_femas_process_cpu[2m])"
    }
   ]
  },
  {
   "title": "Page Faults (count)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "roq_femas_process_faults" }
   ]
  },
  {
   "title": "Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(roq_femas_process_memory) / 1048576"
    }
   ]
  },
  {
   "title": "Experiments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 * (sum(roq_femas_gateway_order_update{type=\"completed\"}) / sum(roq_femas_gateway_order_action{type=\"create_order\"}))"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "roq_femas_gateway_exceptions" }
     ]
    }
   ]
  }
 ]
}