{
 "title": "roq-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "max(node_hwmon_temp_celsius)" }
   ]
  },
  {
   "title": "Frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_cpu_frequency_hertz) / 1000 / 1000 / 1000"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    { "expr": "irate(node_intr_total[1m])" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_Active_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "EDAC",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_edac_uncorrectable_errors_total"
    }
   ]
  },
  {
   "title": "Device Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_device_error)"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "1 - (max(node_filesystem_free_bytes{device!=\"tmpfs\"}) by (device) / max(node_filesystem_size_bytes{device!=\"tmpfs\"}) by (device))"
    }
   ]
  },
  {
   "title": "Critical Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_hwmon_temp_crit_celsius)"
    }
   ]
  },
  {
   "title": "Max Frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_cpu_frequency_max_hertz) / 1000 / 1000 / 1000"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(node_context_switches_total[1m])"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_Dirty_bytes" }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))"
    }
   ]
  },
  { "title": "Coinbase PRO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"coinbase-pro\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Market Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"coinbase-pro\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"coinbase-pro\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "roq_exceptions{source=\"coinbase-pro\"}"
    }
   ]
  },
  {
   "title": "Events (total)",
   "type": "singlestat",
   "description": "Quickly spot\n\n(a) how much has been processed,\n(b) is the feed good, and\n(c) has the service restarted.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(roq_events_count{source=\"coinbase-pro\"})"
    }
   ]
  },
  {
   "title": "Events (frequency)",
   "type": "graph",
   "description": "Quickly spot\n\n(a) how much has been processed,\n(b) is the feed good, and\n(c) has the service restarted.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(roq_events_count{source=\"coinbase-pro\"}[1m])"
    }
   ]
  },
  {
   "title": "External (latency)",
   "type": "graph",
   "description": "Represented as a 1-way latency.\n\nCan be measured as\n\n(a) half the time to receive a reply to a heartbeat request, or\n(b) the difference between current time and a timestamp originated from the exchange.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(roq_latency_sum{source=\"coinbase-pro\"}[1m]) / on(source, connection, function) rate(roq_latency_count{source=\"coinbase-pro\"}[1m]) / 1000000"
    }
   ]
  },
  {
   "title": "Disconnect",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "count by (connection) (roq_counter{source=\"coinbase-pro\",function=\"disconnect\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Market by Price",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_profile_count{source=\"coinbase-pro\", function=\"market_by_price\"}[1m]))"
    }
   ]
  },
  {
   "title": "Working Orders",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(roq_clients{source=\"coinbase-pro\", event=\"connect\"}) - max(roq_clients{source=\"coinbase-pro\", event=\"disconnect\"})"
    }
   ]
  },
  { "title": "Deribit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"deribit\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Market Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"deribit\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"deribit\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "roq_exceptions{source=\"deribit\"}"
    }
   ]
  },
  {
   "title": "Events (total)",
   "type": "singlestat",
   "description": "Quickly spot\n\n(a) how much has been processed,\n(b) is the feed good, and\n(c) has the service restarted.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(roq_events_count{source=\"deribit\"})"
    }
   ]
  },
  {
   "title": "Events (frequency)",
   "type": "graph",
   "description": "Quickly spot\n\n(a) how much has been processed,\n(b) is the feed good, and\n(c) has the service restarted.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(roq_events_count{source=\"deribit\"}[1m])"
    }
   ]
  },
  {
   "title": "External (latency)",
   "type": "graph",
   "description": "Represented as 1-way latencyRepresented as a 1-way latency.\n\nCan be measured as\n\n(a) half the time to receive a reply to a heartbeat request, or\n(b) the difference between current time and a timestamp originated from the exchange.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(roq_latency_sum{source=\"deribit\"}[1m]) / on(source, connection, function) rate(roq_latency_count{source=\"deribit\"}[1m]) / 1000000"
    }
   ]
  },
  {
   "title": "Disconnect",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "count by (connection) (roq_counter{source=\"deribit\",function=\"disconnect\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Market by Price",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_profile_count{source=\"deribit\", function=\"market_by_price\"}[1m]))"
    }
   ]
  },
  {
   "title": "Working Orders",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(roq_clients{source=\"deribit\", event=\"connect\"}) - max(roq_clients{source=\"deribit\", event=\"disconnect\"})"
    }
   ]
  },
  {
   "title": "Market by Price",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roq_profile_count{source=\"gemini\", function=\"market_by_price\"}[1m]))"
    }
   ]
  },
  {
   "title": "Working Orders",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(roq_clients{source=\"gemini\", event=\"connect\"}) - max(roq_clients{source=\"deribit\", event=\"disconnect\"})"
    }
   ]
  },
  { "title": "Gemini", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"gemini\",connection=\"process\",state=\"heartbeat\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Market Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"gemini\",connection=\"market_data\",state=\"ready\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Order Manager",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(absent(roq_updated{source=\"gemini\",connection=\"order_manager\",state=\"ready\"}) OR vector(0))"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "roq_exceptions{source=\"gemini\"}"
    }
   ]
  },
  {
   "title": "Events (total)",
   "type": "singlestat",
   "description": "Quickly spot\n\n(a) how much has been processed,\n(b) is the feed good, and\n(c) has the service restarted.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(roq_events_count{source=\"gemini\"})"
    }
   ]
  },
  {
   "title": "Events (frequency)",
   "type": "graph",
   "description": "Quickly spot\n\n(a) how much has been processed,\n(b) is the feed good, and\n(c) has the service restarted.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(roq_events_count{source=\"gemini\"}[1m])"
    }
   ]
  },
  {
   "title": "External (latency)",
   "type": "graph",
   "description": "Represented as 1-way latencyRepresented as a 1-way latency.\n\nCan be measured as\n\n(a) half the time to receive a reply to a heartbeat request, or\n(b) the difference between current time and a timestamp originated from the exchange.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(roq_latency_sum{source=\"gemini\"}[1m]) / on(source, connection, function) rate(roq_latency_count{source=\"gemini\"}[1m]) / 1000000"
    }
   ]
  },
  {
   "title": "Disconnect",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "count by (connection) (roq_counter{source=\"gemini\",function=\"disconnect\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Working Orders",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "Internal Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 10, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{function=~\"create_order|modify_order|cancel_order\"}[1m])) by(source)"
      }
     ]
    },
    {
     "title": "Awaiting Response",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 10, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(roq_profile_count{function=~\"create_order|modify_order|cancel_order\"}[1m])) by(source) - sum(irate(roq_profile_count{function=~\"create_order_ack|modify_order_ack|cancel_order_ack\"}[1m])) by(source)"
      }
     ]
    }
   ]
  },
  { "title": "Debug (gateways)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Events (encoded messages)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    { "expr": "irate(roq_events_count[1m])" }
   ]
  },
  {
   "title": "Events (encode latency)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_events_sum[1m]) / on (source, function) irate(roq_events_count[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Encoding > .5μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_events_bucket{le=\"500\"}[1m]) / on (source, function) irate(roq_events_count[1m])"
    }
   ]
  },
  {
   "title": "Encoding > 1μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_events_bucket{le=\"1000\"}[1m]) / on (source, function) irate(roq_events_count[1m])"
    }
   ]
  },
  {
   "title": "Encoding > 2μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_events_bucket{le=\"2000\"}[1m]) / on (source, function) irate(roq_events_count[1m])"
    }
   ]
  },
  {
   "title": "Profile (measurements)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    { "expr": "irate(roq_profile_count[1m])" }
   ]
  },
  {
   "title": "Profile (processing latency)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_profile_sum[1m]) / on (source, connection, function) irate(roq_profile_count[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Processing > 2μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_profile_bucket{le=\"2000\"}[1m]) / on (source, connection, function) irate(roq_profile_count[1m])"
    }
   ]
  },
  {
   "title": "Processing > 5μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_profile_bucket{le=\"5000\"}[1m]) / on (source, connection, function) irate(roq_profile_count[1m])"
    }
   ]
  },
  {
   "title": "Processing > 10μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_profile_bucket{le=\"10000\"}[1m]) / on (source, connection, function) irate(roq_profile_count[1m])"
    }
   ]
  },
  {
   "title": "Heartbeat (client <--> server latency)",
   "type": "graph",
   "description": "Represented as 1-way latency",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(roq_heartbeat_latency_sum[1m]) / on (receiver, sender) irate(roq_heartbeat_latency_count[1m]) / 1000"
    }
   ]
  },
  {
   "title": "Heartbeat > 1μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_heartbeat_latency_bucket{le=\"1000\"}[1m]) / on (sender, receiver) irate(roq_heartbeat_latency_count[1m])"
    }
   ]
  },
  {
   "title": "Heartbeat > 2μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_heartbeat_latency_bucket{le=\"2000\"}[1m]) / on (sender, receiver) irate(roq_heartbeat_latency_count[1m])"
    }
   ]
  },
  {
   "title": "Heartbeat > 5μs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - irate(roq_heartbeat_latency_bucket{le=\"5000\"}[1m]) / on (sender, receiver) irate(roq_heartbeat_latency_count[1m])"
    }
   ]
  },
  {
   "title": "Debug (system)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(node_interrupts_total{cpu=~\"[1-6]\",info!~\".*timer.*\"}[1m])"
      }
     ]
    },
    {
     "title": "Major Faults",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgmajfault[1m])"
      }
     ]
    },
    {
     "title": "Minor Faults",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(node_vmstat_pgfault[1m])" }
     ]
    },
    {
     "title": "Pages In",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(node_vmstat_pgpgin[1m])" }
     ]
    },
    {
     "title": "Pages Out",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      { "expr": "irate(node_vmstat_pgpgout[1m])" }
     ]
    }
   ]
  },
  {
   "title": "Feed Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "absent(rate(node_systemd_unit_state{name=\"roq-influxdb.service\",state=\"active\"}[10s])) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Aux",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "InfluxDB",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(node_systemd_unit_state{name=\"influxdb.service\",state=\"active\"})"
      }
     ]
    },
    {
     "title": "Redis",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceil(node_systemd_unit_state{name=\"redis.service\",state=\"active\"})"
      }
     ]
    }
   ]
  }
 ]
}