---

roq_hitbtc_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-hitbtc"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "hitbtc"
    config_file: "{{ directory_config.usr_local_etc }}/roq-hitbtc/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-hitbtc.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-hitbtc.sock"
    ws_uri: "wss://hitbtc.com/ws"
    # fix_uri: "tcp+ssl://fix.hitbtc.com:4364"
  symbols:
    - ".*"
