---

roq_hitbtc_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-hitbtc"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "hitbtc"
    config_file: "{{ root }}/usr/local/etc/roq-hitbtc/config.toml"
    event_log_dir: "{{ root }}/var/lib/roq/event-logs"
    client_listen_address: "{{ root }}/run/roq/roq-hitbtc.sock"
    metrics_listen_address: "{{ root }}/run/roq/metrics/roq-hitbtc.sock"
    ws_uri: "wss://hitbtc.com/ws"
    rest_uri: "https://hitbtc.com"
    fix_uri: "tcp+ssl://fix.hitbtc.com:4364"
  symbols:
    - ".*"
