---

##############
### DEBIAN ###
##############

- block:

  - name: install tools
    apt:
      name: virtualbox
      state: present

  when: ansible_os_family == "Debian" and become_user is defined
  become: true
  tags:
    - virtualbox
  
##############
### REDHAT ###
##############

- block:

  - name: install tools
    yum:
      name: virtualbox
      state: present

  when: ansible_os_family == "RedHat" and become_user is defined
  become: true
  tags:
    - virtualbox
