---

##############
### DEBIAN ###
##############

- block:

  - name: install
    apt:
      name: virtualbox
      state: present

  when: ansible_os_family == "Debian" and become_user is defined
  become: true
  tags:
    - virtualbox
  
##############
### REDHAT ###
##############

- block:

  - name: install dkms
    yum:
      name: dkms
      state: present

  - name: download repo
    get_url:
      url: "http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo"
      dest: "/etc/yum.repos.d/virtualbox.repo"

  - name: install
    yum:
      name: "VirtualBox-{{ virtualbox_defaults.version }}"
      state: present

  when: ansible_os_family == "RedHat" and become_user is defined
  become: true
  tags:
    - virtualbox
