---

- block:

  - name: create clickhouse config
    set_fact:
      clickhouse_config: >
          {{ clickhouse_defaults | combine(clickhouse | default({}), recursive=True) }}
      cacheable: true

  - name: create grafana config
    set_fact:
      grafana_config: >
          {{ grafana_defaults | combine(grafana | default({}), recursive=True) }}
      cacheable: true

  - name: create gogs config
    set_fact:
      gogs_config: >
          {{ gogs_defaults | combine(gogs | default({}), recursive=True) }}
      cacheable: true

  - name: create influxdb config
    set_fact:
      influxdb_config: >
          {{ influxdb_defaults | combine(influxdb | default({}), recursive=True) }}
      cacheable: true

  - name: create nginx config
    set_fact:
      nginx_config: >
          {{ nginx_defaults | combine(nginx | default({}), recursive=True) }}
      cacheable: true

  - name: create redis config
    set_fact:
      redis_config: >
          {{ redis_defaults | combine(redis | default({}), recursive=True) }}
      cacheable: true

  tags:
    - always
