---

roq_clickhouse_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-clickhouse"
  name: "clickhouse"
  logging:
    verbosity: 0
  options:
    name: "clickhouse"
    uri: "http://localhost:8123"
    database: "roq"
    create_database: true
