---

roq_clickhouse_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-clickhouse"
  name: "clickhouse"
  logging:
    verbosity: 0
  flags:
    name: "clickhouse"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-clickhouse.sock"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    uri: "http://localhost:8123"
    database_name: "roq"
