---

roq_deribit_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-deribit"
  service:
    start: "Mon-Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  cpu_affinity: {}
  logging:
    verbosity: 0
  name: "deribit"
  net:
    fix: "tcp://test.deribit.com:9881"
    ws: "wss://test.deribit.com/ws/api/v2"
  event_log:
    dir: "{{ root }}/var/lib/roq"
    sync_freq_secs: 600
  options: {}
  symbols:
    - ".*"
