---

roq_deribit_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-deribit"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "deribit"
    config_file: "{{ directory_config.usr_local_etc }}/roq-deribit/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-deribit.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-deribit.sock"
    ws_uri: "wss://test.deribit.com/ws/api/v2"
    fix_uri: "tcp://test.deribit.com:9881"
  symbols:
    include:
      - ".*"
    exclude:
      - ".*USDT.*"
