---

roq_deribit_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-deribit"
  cpu: {}
  logging:
    verbosity: 0
  collect:
    size: 0
    path: "{{ root }}/var/tmp/roq-deribit.roq"
    sync_freq_secs: 600
