---

roq_deribit_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-deribit"
  cpu_affinity: {}
  logging:
    verbosity: 0
  event_log:
    dir: "{{ root }}/var/lib/roq/deribit/"
    sync_freq_secs: 600
  options: {}
