---

roq_deribit_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-deribit"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "deribit"
    config_file: "{{ root }}/etc/roq/roq-deribit.toml"
    event_log_dir: "{{ root }}/var/lib/roq"
    client_listen_address: "{{ root }}/var/tmp/roq-deribit.sock"
    metrics_listen_address: "{{ root }}/var/tmp/roq-deribit_metrics.sock"
    ws_uri: "wss://test.deribit.com/ws/api/v2"
    fix_uri: "tcp://test.deribit.com:9881"
  symbols:
    include:
      - ".*"
    exclude:
      - "USDT-.*"
