---

- name: detect owner
  set_fact:
    user: "{{ user if roq_user is defined else ansible_user_id }}"
  tags:
    - roq-benchmark

- name: combine configuration with defaults
  set_fact:
    test_config: '{{ benchmark_defaults | combine(benchmark | default({})) }}'
  tags:
    - roq-benchmark

- block:

  - name: create required directories
    file:
      path: "{{ root }}/{{ item }}"
      state: directory
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0770
    with_items:
      - "/var/lib/roq"
      - "/var/log/roq"
      - "/var/run/roq"
      - "/var/run/roq/test"

  - name: create ping run scripts
    template:
      src: "templates/roq-ping.sh"
      dest: "{{ root }}/usr/local/bin/roq-ping-{{ item }}.sh"
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0750
    with_sequence: 1-2

  - name: create pong run scripts
    template:
      src: "templates/roq-pong.sh"
      dest: "{{ root }}/usr/local/bin/roq-pong-{{ item }}.sh"
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0750
    with_sequence: 1-2

  - name: install the roq-benchmark conda package
    shell: "{{ root }}/miniconda/bin/conda install -y -n base roq-benchmark{{ '' if test_config.version == 'latest' else '==%s'|format(test_config.version) }}"
  
  become: become_user is defined
  tags:
    - roq-benchmark

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ test_config.docker.name }}"
      tag: "{{ test_config.version }}"
      source: pull
      force_tag: true
      build:
        http_timeout: 600

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - 'roq-ping-1.service'
      - 'roq-ping-2.service'
      - 'roq-pong-1.service'
      - 'roq-pong-2.service'

#  - name: create systemd units
#    template:
#      src: "templates/{{ item }}"
#      dest: "/etc/systemd/system/{{ item }}"
#      owner: root
#      group: root
#      mode: 0644
#    with_items: "{{ systemd_units }}"

  - name: create ping systemd units
    template:
      src: "templates/roq-ping.service"
      dest: "{{ root }}/etc/systemd/system/roq-ping-{{ item }}.service"
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0750
    with_sequence: 1-2

  - name: create pong systemd units
    template:
      src: "templates/roq-pong.service"
      dest: "{{ root }}/etc/systemd/system/roq-pong-{{ item }}.service"
      owner: "{{ user }}"
      # group: "{{ user }}"
      mode: 0750
    with_sequence: 1-2

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  when: become_user is defined and 'roq_benchmark' in group_names
  become: true
  tags:
    - roq-benchmark
