---

roq_ftx_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-ftx"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "ftx"
    config_file: "{{ root }}/usr/local/etc/roq-ftx/config.toml"
    event_log_dir: "{{ root }}/var/lib/roq/event-logs"
    client_listen_address: "{{ root }}/run/roq/roq-ftx.sock"
    metrics_listen_address: "{{ root }}/run/roq/metrics/roq-ftx.sock"
    ws_uri: "wss://ftx.com/ws"
    rest_uri: "https://ftx.com"
    fix_uri: "tcp+ssl://fix.ftx.com:4364"
  symbols:
    - ".*"
