---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ root }}/usr/local/etc/prometheus"
      - "{{ root }}/var/lib/prometheus"
      - "{{ root }}/usr/local/etc/alertmanager"
      - "{{ root }}/var/lib/alertmanager"
    notify:
    - restart prometheus
    - restart alertmanager
  
  - name: create config files
    template:
      src: "templates/{{ item | basename }}"
      dest: "{{ root }}/usr/local/etc/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - "prometheus/prometheus.yml"
      - "prometheus/alert.rules"
      - "alertmanager/alertmanager.yml"
    notify:
    - restart prometheus
    - restart alertmanager
  
  - name: pull docker images
    docker_image:
      name: "{{ item }}"
      source: pull
      force_source: true
      force_tag: true
    with_items:
      - "{{ docker_registry_prefix | default('') }}{{ node_exporter_config.docker.name }}:{{ node_exporter_config.docker.tag }}"
      - "{{ docker_registry_prefix | default('') }}{{ prometheus_config.docker.name }}:{{ prometheus_config.docker.tag }}"
      - "{{ docker_registry_prefix | default('') }}{{ alertmanager_config.docker.name }}:{{ alertmanager_config.docker.tag }}"
    notify:
    - restart prometheus
    - restart alertmanager

  ##################
  ### PROMETHEUS ###
  ##################
  
  - name: create prometheus systemd service
    template:
      src: "templates/prometheus.service"
      dest: "/etc/systemd/system/prometheus.service"
      owner: root
      group: root
      mode: 0644
    register: prometheus_service
    notify:
    - restart prometheus
  
  - name: enable the prometheus service
    systemd:
      name: "prometheus.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: prometheus_service.changed
  
  #####################
  ### NODE-EXPORTER ###
  #####################
  
  - name: create node-exporter systemd service
    template:
      src: "templates/node-exporter.service"
      dest: "/etc/systemd/system/node-exporter.service"
      owner: root
      group: root
      mode: 0644
    register: node_exporter_service
    notify:
    - restart node-exporter
  
  - name: enable the node-exporter service
    systemd:
      name: "node-exporter.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: node_exporter_service.changed
  
  ####################
  ### ALERTMANAGER ###
  ####################
  
  - name: create alertmanager systemd service
    template:
      src: "templates/alertmanager.service"
      dest: "/etc/systemd/system/alertmanager.service"
      owner: root
      group: root
      mode: 0644
    register: alertmanager_service
    notify:
    - restart alertmanager
  
  - name: enable the alertmanager service
    systemd:
      name: "alertmanager.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: alertmanager_service.changed

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - prometheus
