---

#################################
### WORKS WITHOUT BECOME_USER ###
#################################

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0755
    with_items:
      - "{{ directory_config.var_lib }}/roq"
      - "{{ directory_config.var_lib }}/roq/data"
      - "{{ directory_config.usr_local_etc }}//roq-{{ config.flags.name }}"

  - name: create config and flagfile
    template:
      src: "gateway/{{ item }}"
      dest: "{{ directory_config.usr_local_etc }}/roq-{{ config.flags.name }}"
      mode: 0644
    with_items:
      - "flags.cfg"
      - "config.toml"

  - name: create shell script
    template:
      src: "gateway/{{ item | basename }}"
      dest: "{{ item | dirname }}/roq-{{ item | basename | replace('item', config.flags.name) }}"
      mode: 0755
    with_items:
      - "{{ directory_config.usr_local_bin }}/item"

  - name: check previous version
    shell: '{{ directory_config.opt }}/conda/bin/conda list -f roq-{{ config.flags.name }} | sed -n "s/^roq-{{ config.flags.name }}\s*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"'
    register: previous_version
    changed_when: false

  - name: install conda package
    shell: "{{ directory_config.opt }}/conda/bin/conda install -y -n base 
      roq-{{ config.flags.name }}{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
    changed_when: false
  
  - name: check current version
    shell: '{{ directory_config.opt }}/conda/bin/conda list -f roq-{{ config.flags.name }} | sed -n "s/^roq-{{ config.flags.name }}\s*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"'
    register: current_version
    changed_when: "current_version.stdout != previous_version.stdout"

  become: "{{ 'true' if become_user is defined else 'false' }}"

############################################
### ONLY IF BECOME_USER HAS BEEN DEFINED ###
############################################

- block:

  - name: create systemd files
    template:
      src: "gateway/{{ item | basename }}"
      dest: "{{ item | dirname }}/roq-{{ item | basename | replace('item', config.flags.name) }}"
      mode: "{{ '0755' if (item | splitext | last == '.sh') else '0644' }}"
    with_items:
      - "/etc/systemd/system/item.service"
      - "/etc/systemd/system/item.timer"
      - "/etc/systemd/system/item-stop.service"
      - "/etc/systemd/system/item-stop.timer"

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ config.docker.name }}"
      tag: "{{ config.version }}"
      source: pull
      force_source: true
      force_tag: true
    when: config.docker.use

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'roq-{{ config.flags.name }}.service'
      - 'roq-{{ config.flags.name }}-stop.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'roq-{{ config.flags.name }}.timer'
      - 'roq-{{ config.flags.name }}-stop.timer'

  - name: disable systemd services
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_services }}"

  - name: enable systemd timers
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items: "{{ systemd_timers }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

  when: become_user is defined
  become: true
