---

- name: combine user configuration with defaults
  set_fact:
    roq_huobi_config: >
        {{ roq_huobi_defaults | combine(roq_huobi | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- block:

  - name: shorter variable name for config
    set_fact:
      config: "{{ roq_huobi_config }}"

  - name: install
    include_role:
      name: common
      tasks_from: gateway

  when: "'roq_huobi' in group_names"
  tags:
    - roq-huobi
