---

roq_binance_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-binance"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "binance"
    config_file: "{{ root }}/etc/roq/roq-binance.toml"
    event_log_dir: "{{ root }}/var/lib/roq"
    client_listen_address: "{{ root }}/var/tmp/roq-binance.sock"
    metrics_listen_address: "{{ root }}/var/tmp/roq-binance_metrics.sock"
    rest_uri: "https://testnet.binance.com"
    ws_uri: "wss://testnet.binance.com/realtime"
    cache_mbp_allow_price_inversion: true
  symbols:
    - ".*"
