---

roq_binance_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-binance"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  options:
    name: "binance"
    config_file: "{{ directory_config.usr_local_etc }}/roq-binance/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-binance.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-binance.sock"
    rest_uri: "https://testnet.binance.com"
    ws_uri: "wss://testnet.binance.com/realtime"
    cache_mbp_allow_price_inversion: true
  symbols:
    - ".*"
