---

- block:

  - name: create required directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ root }}/opt/conda"
  
  - name: download {{ anaconda.url }}/miniconda/{{ miniconda_sh }}
    get_url:
      url: "{{ anaconda.url }}/miniconda/{{ miniconda_sh }}"
      dest: "{{ root }}/opt"
      mode: 0644
  
  - name: create {{ root }}/usr/local/bin/{{ miniconda_sh }}
    file:
      src: "{{ root }}/opt/{{ miniconda_sh }}"
      dest: "{{ root }}/usr/local/bin/{{ miniconda_sh }}"
      owner: "{{ roq_user }}"
      state: link
  
  - name: install {{ root }}/conda
    shell: "bash {{ root }}/usr/local/bin/{{ miniconda_sh }} -b -u -p {{ root }}/opt/conda"
    args:
      creates: "{{ root }}/opt/conda/bin/activate"
  
  - name: create {{ root }}/opt/conda/.condarc
    template:
      src: "templates/condarc"
      dest: "{{ root }}/opt/conda/.condarc"
      mode: 0644
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - conda
