---

- block:

  - name: create required directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ directory_config.opt }}/conda"
  
  - name: download installer
    get_url:
      url: "{{ conda.url }}/{{ conda.script }}"
      dest: "{{ directory_config.opt }}"
      mode: 0644
  
  - name: install
    shell: "bash {{ directory_config.opt }}/{{ conda.script }} -b -u -p {{ directory_config.opt }}/conda"
    args:
      creates: "{{ directory_config.opt }}/conda/bin/activate"
  
  - name: create .condarc
    template:
      src: "templates/condarc"
      dest: "{{ directory_config.opt }}/conda/.condarc"
      mode: 0644
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - conda
