global:
  scrape_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ['alertmanager.service:{{ alertmanager.port }}']

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus.service:{{ prometheus.port }}']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter.service:{{ node_exporter.port }}']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['netdata.service:{{ netdata.port }}']
{% if 'roq-femas' in groups %}

  - job_name: 'roq_femas'
    scrape_interval: 5s
    static_configs:
{% if femas_use_docker %}
      - targets: ['roq-femas.service:{{ roq_femas.metrics.port }}']
{% else %}
      - targets: ['roq-femas-unix-to-tcp.service:{{ roq_femas.metrics.port }}']
{% endif %}
{% endif %}
{% if 'roq-datafeed' in groups %}

  - job_name: 'roq_datafeed'
    scrape_interval: 5s
    static_configs:
{% if datafeed_use_docker %}
      - targets: ['roq-datafeed.service:{{ roq_datafeed.metrics.port }}']
{% else %}
      - targets: ['roq-datafeed-unix-to-tcp.service:{{ roq_datafeed.metrics.port }}']
{% endif %}
{% endif %}
{% if 'roq-test' in groups %}
{% for i in range(1, 3) %}

  - job_name: 'server-{{ i }}'
    metrics_path: '/metrics/server-{{ i }}'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endfor %}
{% for i in range(1, 3) %}

  - job_name: 'client-{{ i }}'
    metrics_path: '/metrics/client-{{ i }}'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endfor %}
{% endif %}
