global:
  scrape_interval: 5s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ['alertmanager.service:{{ alertmanager.port }}']

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.service:{{ prometheus.port }}']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter.service:{{ node_exporter.port }}']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['netdata.service:{{ netdata.port }}']
{% if 'roq_benchmark' in groups %}
{% for i in range(1, 3) %}

  - job_name: 'roq-ping-{{ i }}'
    metrics_path: '/metrics/roq-ping-{{ i }}'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endfor %}
{% for i in range(1, 3) %}

  - job_name: 'roq-pong-{{ i }}'
    metrics_path: '/metrics/roq-pong-{{ i }}'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endfor %}
{% endif %}
{% if 'roq_simulator' in groups %}

  - job_name: 'roq-simulator'
    metrics_path: '/metrics/roq-simulator'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_influxdb' in groups %}

  - job_name: 'roq-influxdb'
    metrics_path: '/metrics/roq-influxdb'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_bitmex' in groups %}

  - job_name: 'roq-bitmex'
    metrics_path: '/metrics/roq-bitmex'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_bitstamp' in groups %}

  - job_name: 'roq-bitstamp'
    metrics_path: '/metrics/roq-bitstamp'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_coinbase_pro' in groups %}

  - job_name: 'roq-coinbase-pro'
    metrics_path: '/metrics/roq-coinbase-pro'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_deribit' in groups %}

  - job_name: 'roq-deribit'
    metrics_path: '/metrics/roq-deribit'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_ftx' in groups %}

  - job_name: 'roq-ftx'
    metrics_path: '/metrics/roq-ftx'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_gemini' in groups %}

  - job_name: 'roq-gemini'
    metrics_path: '/metrics/roq-gemini'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
{% if 'roq_hitbtc' in groups %}

  - job_name: 'roq-hitbtc'
    metrics_path: '/metrics/roq-hitbtc'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['nginx.service:80']
{% endif %}
