---

- block:

  - name: create run scripts
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/usr/local/bin/{{ item }}"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0750
    with_items:
      - "roq-backup.sh"

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'roq-backup.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'roq-backup.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

  when: become_user is defined
  become: true
  tags:
    - roq-backup
