---

- name: combine user configuration with defaults
  set_fact:
    roq_hitbtc_config: >
        {{ roq_hitbtc_defaults | combine(roq_hitbtc | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- block:

  - name: shorter variable name for config
    set_fact:
      config: "{{ roq_hitbtc_config }}"

  - name: install
    include_role:
      name: common
      tasks_from: gateway

  when: "'roq_hitbtc' in group_names"
  tags:
    - roq-hitbtc
