---

- name: combine user configuration with defaults
  set_fact:
    roq_gemini_config: >
        {{ roq_gemini_defaults | combine(roq_gemini | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- name: configuration (debug)
  debug:
    var: config
    verbosity: 1
  tags:
    - always

- name: shorter variable name for config
  set_fact:
    config: "{{ roq_gemini_config }}"
  tags:
    - roq-gemini

- block:

  - name: create required directories
    file:
      path: "{{ root }}/{{ item }}"
      state: directory
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0770
    with_items:
      - "/etc/roq"
      - "/var/lib/roq"
      - "/var/lib/roq/roq-gemini"
      - "/var/log/roq"
      - "/var/run/roq"

  - name: create config files
    template:
      src: "templates/{{ item | basename }}"
      dest: "{{ root }}/etc/roq/{{ item }}"
      owner: "{{ roq_user }}"
      group: "{{ roq_user }}"
      mode: 0644
    with_items:
      - "roq-gemini.toml"
      - "roq-gemini.gflags"

  - name: create run scripts
    template:
      src: "templates/{{ item }}"
      dest: "{{ root }}/usr/local/bin/{{ item }}"
      owner: "{{ roq_user }}"
      # group: "{{ roq_user }}"
      mode: 0750
    with_items:
      - "roq-gemini.sh"
      - "roq-gemini-backup.sh"

  - name: install the roq-gemini conda package
    shell: "{{ root }}/miniconda/bin/conda install -y -n base \
      roq-gemini{{ '' if config.version == 'latest' else '==%s'|format(config.version) }}"
  
  when: "'roq_gemini' in group_names"
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - roq-gemini

##############
### SERVER ###
##############

- block:

  - name: docker pull images
    docker_image:
      name: "{{ docker_registry_prefix | default('') }}{{ config.docker.name }}"
      tag: "{{ config.version }}"
      source: pull
      force_source: true
      force_tag: true
      build:
        http_timeout: 600
    when: config.docker.use

  - name: define list of systemd services
    set_fact:
      systemd_services:
      - 'roq-gemini.service'
      - 'roq-gemini-stop.service'
      - 'roq-gemini-backup.service'

  - name: define list of systemd timers
    set_fact:
      systemd_timers:
      - 'roq-gemini.timer'
      - 'roq-gemini-stop.timer'
      - 'roq-gemini-backup.timer'

  - name: define list of systemd units
    set_fact:
      systemd_units:
      - '{{ systemd_services }} + {{ systemd_timers }}'

  - name: create systemd units
    template:
      src: "templates/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"

  - name: enable systemd units
    systemd:
      name: "{{ item }}"
      enabled: false
      daemon_reload: true
    with_items: "{{ systemd_units }}"

  - name: start systemd timers
    systemd:
      name: "{{ item }}"
      state: started
    with_items: "{{ systemd_timers }}"

  when: become_user is defined and 'roq_gemini' in group_names
  become: true
  tags:
    - roq-gemini
